### ISSUE TITLE
Don't ignore SIGINT

### ISSUE THREAD

**Issue by jaredbeck** [heroku/heroku#1035]
`heroku run rails console`

After not using a remote rails console for a while (15+ minutes) it becomes unresponsive.  Perhaps the server hung up?  Anyway, the client ignores ctrl-D (end of input) and ctrl-C (SIGINT). 

I used ctrl-Z, `kill -2 [pid]`, and `fg` and then saw the following:

```
heroku run rails console -a givegab-demo

 !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       uninitialized constant Heroku::Command::RestClient (NameError)
    Backtrace:   /Users/jared/.heroku/client/lib/heroku/command.rb:225:in `rescue in run'
                 /Users/jared/.heroku/client/lib/heroku/command.rb:273:in `run'
                 /Users/jared/.heroku/client/lib/heroku/cli.rb:28:in `start'
                 /usr/local/heroku/bin/heroku:24:in `<main>'

    Command:     heroku run rails console -a givegab-demo
    Plugins:     heroku-accounts
                 heroku-pg-extras

    Version:     heroku-toolbelt/3.3.0 (x86_64-darwin10.8.0) ruby/1.9.3
```

**Comment by jaredbeck** [comment]
This issue is almost one year old, and never received any attention.  I guess I'll just close it.
