### ISSUE TITLE
heroku login failed behind proxy on windows 7

### ISSUE THREAD

**Issue by ThomasZhou** [heroku/heroku#1060]
```
D:\>heroku login
Enter your Heroku credentials.
Email: 
Password (typing will be hidden):
 !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       Unable to verify certificate, please set `Excon.defaults[:ssl_ca_path] = path_to_certs`, `ENV['SSL_CERT
_DIR'] = path_to_certs`, `Excon.defaults[:ssl_ca_file] = path_to_file`, `ENV['SSL_CERT_FILE'] = path_to_file` or `Excon.
defaults[:ssl_verify_peer] = false` (less secure). (Excon::Errors::SocketError)
    Backtrace:   C:/Program Files/Heroku/vendor/gems/excon-0.25.3/lib/excon/ssl_socket.rb:66:in `connect'
                 C:/Program Files/Heroku/vendor/gems/excon-0.25.3/lib/excon/ssl_socket.rb:66:in `initialize'
                 C:/Program Files/Heroku/vendor/gems/excon-0.25.3/lib/excon/connection.rb:361:in `new'
                 C:/Program Files/Heroku/vendor/gems/excon-0.25.3/lib/excon/connection.rb:361:in `socket'
                 C:/Program Files/Heroku/vendor/gems/excon-0.25.3/lib/excon/connection.rb:105:in `request_call'
                 C:/Program Files/Heroku/vendor/gems/excon-0.25.3/lib/excon/middlewares/mock.rb:42:in `request_call'
                 C:/Program Files/Heroku/vendor/gems/excon-0.25.3/lib/excon/middlewares/instrumentor.rb:22:in `request_c
all'
                 C:/Program Files/Heroku/vendor/gems/excon-0.25.3/lib/excon/middlewares/base.rb:15:in `request_call'
                 C:/Program Files/Heroku/vendor/gems/excon-0.25.3/lib/excon/middlewares/base.rb:15:in `request_call'
                 C:/Program Files/Heroku/vendor/gems/excon-0.25.3/lib/excon/middlewares/base.rb:15:in `request_call'
                 C:/Program Files/Heroku/vendor/gems/excon-0.25.3/lib/excon/connection.rb:244:in `request'
                 C:/Program Files/Heroku/vendor/gems/heroku-api-0.3.15/lib/heroku/api.rb:76:in `request'
                 C:/Program Files/Heroku/vendor/gems/heroku-api-0.3.15/lib/heroku/api/login.rb:9:in `post_login'
                 C:/Program Files/Heroku/lib/heroku/auth.rb:80:in `api_key'
                 C:/Program Files/Heroku/lib/heroku/auth.rb:189:in `ask_for_credentials'
                 C:/Program Files/Heroku/lib/heroku/auth.rb:221:in `ask_for_and_save_credentials'
                 C:/Program Files/Heroku/lib/heroku/auth.rb:84:in `get_credentials'
                 C:/Program Files/Heroku/lib/heroku/auth.rb:41:in `login'
                 C:/Program Files/Heroku/lib/heroku/command/auth.rb:31:in `login'
                 C:/Program Files/Heroku/lib/heroku/command.rb:218:in `run'
                 C:/Program Files/Heroku/lib/heroku/cli.rb:28:in `start'
                 C:/Program Files/Heroku/bin/heroku:29:in `<main>'

    Command:     heroku login
    HTTP Proxy:  http://127.0.0.1:3128
    HTTPS Proxy: http://127.0.0.1:3128
    Version:     heroku/toolbelt/3.2.0 (i386-mingw32) ruby/1.9.3
```

**Comment by jvbreen1** [comment]
@ThomasZhou were you able to resolve this issue?

**Comment by ransombriggs** [comment]
@jvbreen1 Can you paste in the error that you are receiving?  As this issue is outdated, I suspect you are getting an error at a different spot in the toolbelt execution, and I want to make sure my suggestion works for you using the current version of the toolbelt.

If you are getting this exact error, could you please try setting `ENV['SSL_CERT
_DIR'] = path_to_certs` or `ENV['SSL_CERT_FILE'] = path_to_file` for the certificate authority that your proxy server uses to sign certificates?

**Comment by jvbreen1** [comment]
Sorry, I wasn't clear. I'm not currently having the issue. I was combing through old issues and noticed this one lingering around. Can this issue be closed?

**Comment by ransombriggs** [comment]
Closing issue due to the fact that `heroku login` is no longer in the Ruby code so this will not fail in this way anymore.
