### ISSUE TITLE
undefined method `second_factor='

### ISSUE THREAD

**Issue by andyw8** [heroku/heroku#1345]
```
$ heroku login
Enter your Heroku credentials.
Email: ...
Password (typing will be hidden):
Two-factor code: ...

 !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       undefined method `second_factor=' for #<Heroku::API:0x00000101183ec0> (NoMethodError)
    Backtrace:   /usr/local/heroku/lib/heroku/auth.rb:219:in `ask_for_second_factor'
                 /usr/local/heroku/lib/heroku/auth.rb:92:in `rescue in api_key'
                 /usr/local/heroku/lib/heroku/auth.rb:86:in `api_key'
                 /usr/local/heroku/lib/heroku/auth.rb:214:in `ask_for_credentials'
                 /usr/local/heroku/lib/heroku/auth.rb:262:in `ask_for_and_save_credentials'
                 /usr/local/heroku/lib/heroku/auth.rb:106:in `get_credentials'
                 /usr/local/heroku/lib/heroku/auth.rb:41:in `login'
                 /usr/local/heroku/lib/heroku/command/auth.rb:31:in `login'
                 /usr/local/heroku/lib/heroku/command.rb:221:in `run'
                 /usr/local/heroku/lib/heroku/cli.rb:39:in `start'
                 /usr/local/heroku/bin/heroku:24:in `<main>'

    Command:     heroku login
    Plugins:     heroku-aspen-migrate
                 heroku-config

    Version:     heroku-toolbelt/3.21.3 (x86_64-darwin10.8.0) ruby/1.9.3
```
I'm using the package from Homebrew:
```
$ brew info heroku
heroku-toolbelt: stable 3.20.0
https://toolbelt.heroku.com/other
/usr/local/Cellar/heroku-toolbelt/3.20.0 (438 files, 3.5M) *
  Built from source
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/heroku-toolbelt.rb
```

**Comment by dickeyxxx** [comment]
I think some of the code is on an old version (although I'm not seeing the same bug for some reason) https://github.com/Homebrew/homebrew/pull/35519

**Comment by rounders** [comment]
I'm seeing this error as well after installing the heroku toolbelt today.

**Comment by dickeyxxx** [comment]
what method did you use to install @rounders?

**Comment by rounders** [comment]
@dickeyxxx i downloaded the toolbelt from toolbelt.heroku.com. After encountering the error I then re-installed it using homebrew.

**Comment by aspitz** [comment]
I'm also seeing this exact same error. I didn't use homebrew to install toolbelt, I only installed it from the toolbelt.heroku.com.

**Comment by dickeyxxx** [comment]
the only reason I would think this specific problem would happen is due to old code being around. Try reinstalling, that should certainly fix it.

**Comment by rounders** [comment]
@dickeyxxx I just re-installed and I still run into the problem:

```text
fh-imac $ heroku version
heroku-toolbelt/3.25.0 (x86_64-darwin10.8.0) ruby/1.9.3
You have no installed plugins.
fh-imac $ heroku login                        
Enter your Heroku credentials.
Email: xxxxxxxx@xxxx.xxxx
Password (typing will be hidden): 
Two-factor code: xxxxxx 
Error submitting error.
 !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       undefined method `second_factor=' for #<Heroku::API:0x00000101128a70> (NoMethodError)
    Command:     heroku login
    Version:     heroku-toolbelt/3.25.0 (x86_64-darwin10.8.0) ruby/1.9.3


    More information in /Users/xxxxxx/.heroku/error.log
```


And here is the contents of the error.log log file in case that helps:

```text
exception class/object expected
/usr/local/heroku/lib/heroku/rollbar.rb:9:in `raise'
/usr/local/heroku/lib/heroku/rollbar.rb:9:in `error'
/usr/local/heroku/lib/heroku/helpers.rb:441:in `styled_error'
/usr/local/heroku/lib/heroku/cli.rb:52:in `rescue in start'
/usr/local/heroku/lib/heroku/cli.rb:35:in `start'
/usr/local/heroku/bin/heroku:24:in `<main>'
Heroku client internal error.
undefined method `second_factor=' for #<Heroku::API:0x000001029436f0>
/usr/local/heroku/lib/heroku/auth.rb:219:in `ask_for_second_factor'
/usr/local/heroku/lib/heroku/auth.rb:92:in `rescue in api_key'
/usr/local/heroku/lib/heroku/auth.rb:86:in `api_key'
/usr/local/heroku/lib/heroku/auth.rb:214:in `ask_for_credentials'
/usr/local/heroku/lib/heroku/auth.rb:262:in `ask_for_and_save_credentials'
/usr/local/heroku/lib/heroku/auth.rb:106:in `get_credentials'
/usr/local/heroku/lib/heroku/auth.rb:41:in `login'
/usr/local/heroku/lib/heroku/command/auth.rb:31:in `login'
/usr/local/heroku/lib/heroku/command.rb:223:in `run'
/usr/local/heroku/lib/heroku/cli.rb:40:in `start'
/usr/local/heroku/bin/heroku:24:in `<main>'
exception class/object expected
/usr/local/heroku/lib/heroku/rollbar.rb:9:in `raise'
/usr/local/heroku/lib/heroku/rollbar.rb:9:in `error'
/usr/local/heroku/lib/heroku/helpers.rb:441:in `styled_error'
/usr/local/heroku/lib/heroku/cli.rb:52:in `rescue in start'
/usr/local/heroku/lib/heroku/cli.rb:35:in `start'
/usr/local/heroku/bin/heroku:24:in `<main>'
Heroku client internal error.
undefined method `second_factor=' for #<Heroku::API:0x00000101128a70>
/usr/local/heroku/lib/heroku/auth.rb:219:in `ask_for_second_factor'
/usr/local/heroku/lib/heroku/auth.rb:92:in `rescue in api_key'
/usr/local/heroku/lib/heroku/auth.rb:86:in `api_key'
/usr/local/heroku/lib/heroku/auth.rb:214:in `ask_for_credentials'
/usr/local/heroku/lib/heroku/auth.rb:262:in `ask_for_and_save_credentials'
/usr/local/heroku/lib/heroku/auth.rb:106:in `get_credentials'
/usr/local/heroku/lib/heroku/auth.rb:41:in `login'
/usr/local/heroku/lib/heroku/command/auth.rb:31:in `login'
/usr/local/heroku/lib/heroku/command.rb:223:in `run'
/usr/local/heroku/lib/heroku/cli.rb:40:in `start'
/usr/local/heroku/bin/heroku:24:in `<main>'
```

**Comment by dickeyxxx** [comment]
hmm. I'm still pretty sure you have old code... can you try deleting `/usr/local/heroku` and then reinstalling? Let me know what happens. Also, are you using the osx package?

**Comment by rounders** [comment]
@dickeyxxx thanks, i'll give that a try and will report back shortly.. And yes I'm using the OS X package that I downloaded from  https://toolbelt.heroku.com

**Comment by rounders** [comment]
@dickeyxxx your suggestion of deleting /usr/local/heroku before the re-install did the trick. Thanks!!

**Comment by dickeyxxx** [comment]
thanks for letting me know, now my task if figuring out why that was necessary...

**Comment by benders** [comment]
I had the same problem after downloading a new toolbelt. Deleting `/usr/local/heroku` and then re-installing it also fixed the issue for me. Unfortunately I didn't have the foresight to save that directory before deleting.

```
 !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       undefined method `second_factor=' for #<Heroku::API:0x00000100aacca0> (NoMethodError)
    Command:     heroku ps
    Plugins:     manager-cli
    Version:     heroku-toolbelt/3.37.6 (x86_64-darwin10.8.0) ruby/1.9.3
    Error ID:    b54d32b61dfc49398f436756b0f1e063
```
