### ISSUE TITLE
Misleading error using HTTPS Git Authentication

### ISSUE THREAD

**Issue by stefan-kolb** [heroku/heroku#1397]
Since the default method for Git authentication was changed to HTTPS rather than SSH, I've experienced a strange problem during the push phase.
Everything looks like it is running successfully until the asset precompilation phase.
The asset precomilation errors with this error dump:
At first this looked like a misconfiguration of the Redis Gem, but the same setup goes without any errors if I use the old SSH Git authentication.

``` 
remote: -----> Preparing app for Rails asset pipeline
remote:        Running: rake assets:precompile
remote:        rake aborted!
remote:        invalid url
remote:        /tmp/build_7d1bb159f39028a7b61479242a948632/vendor/bundle/ruby/2.0.0/gems/redis-3.0.6/lib/redis/client.rb:338:in `_parse_options'
remote:        /tmp/build_7d1bb159f39028a7b61479242a948632/vendor/bundle/ruby/2.0.0/gems/redis-3.0.6/lib/redis/client.rb:59:in `initialize'
remote:        /tmp/build_7d1bb159f39028a7b61479242a948632/vendor/bundle/ruby/2.0.0/gems/redis-3.0.6/lib/redis.rb:30:in `new'
remote:        /tmp/build_7d1bb159f39028a7b61479242a948632/vendor/bundle/ruby/2.0.0/gems/redis-3.0.6/lib/redis.rb:30:in `initialize'
remote:        /tmp/build_7d1bb159f39028a7b61479242a948632/vendor/bundle/ruby/2.0.0/gems/redis-store-1.1.4/lib/redis/store.rb:9:in `initialize'
remote:        /tmp/build_7d1bb159f39028a7b61479242a948632/vendor/bundle/ruby/2.0.0/gems/redis-store-1.1.4/lib/redis/store/factory.rb:27:in `new'
remote:        /tmp/build_7d1bb159f39028a7b61479242a948632/vendor/bundle/ruby/2.0.0/gems/redis-store-1.1.4/lib/redis/store/factory.rb:27:in `create'
remote:        /tmp/build_7d1bb159f39028a7b61479242a948632/vendor/bundle/ruby/2.0.0/gems/redis-store-1.1.4/lib/redis/store/factory.rb:10:in `create'
remote:        /tmp/build_7d1bb159f39028a7b61479242a948632/vendor/bundle/ruby/2.0.0/gems/redis-activesupport-4.0.0/lib/active_support/cache/redis_store.rb:28:in `initialize'
remote:        /tmp/build_7d1bb159f39028a7b61479242a948632/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.4/lib/active_support/cache.rb:59:in `new'
remote:        /tmp/build_7d1bb159f39028a7b61479242a948632/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.4/lib/active_support/cache.rb:59:in `lookup_store'
remote:        /tmp/build_7d1bb159f39028a7b61479242a948632/vendor/bundle/ruby/2.0.0/gems/railties-4.0.4/lib/rails/application/bootstrap.rb:62:in `block in <module:Bootstrap>'
remote:        /tmp/build_7d1bb159f39028a7b61479242a948632/vendor/bundle/ruby/2.0.0/gems/railties-4.0.4/lib/rails/initializable.rb:30:in `instance_exec'
remote:        /tmp/build_7d1bb159f39028a7b61479242a948632/vendor/bundle/ruby/2.0.0/gems/railties-4.0.4/lib/rails/initializable.rb:30:in `run'
remote:        /tmp/build_7d1bb159f39028a7b61479242a948632/vendor/bundle/ruby/2.0.0/gems/railties-4.0.4/lib/rails/initializable.rb:55:in `block in run_initializers'
remote:        /tmp/build_7d1bb159f39028a7b61479242a948632/vendor/bundle/ruby/2.0.0/gems/railties-4.0.4/lib/rails/initializable.rb:54:in `run_initializers'
remote:        /tmp/build_7d1bb159f39028a7b61479242a948632/vendor/bundle/ruby/2.0.0/gems/railties-4.0.4/lib/rails/application.rb:215:in `initialize!'
remote:        /tmp/build_7d1bb159f39028a7b61479242a948632/vendor/bundle/ruby/2.0.0/gems/railties-4.0.4/lib/rails/railtie/configurable.rb:30:in `method_missing'
remote:        /tmp/build_7d1bb159f39028a7b61479242a948632/config/environment.rb:9:in `<top (required)>'
remote:        /tmp/build_7d1bb159f39028a7b61479242a948632/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.4/lib/active_support/dependencies.rb:229:in `require'
remote:        /tmp/build_7d1bb159f39028a7b61479242a948632/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.4/lib/active_support/dependencies.rb:229:in `block in require'
remote:        /tmp/build_7d1bb159f39028a7b61479242a948632/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.4/lib/active_support/dependencies.rb:214:in `load_dependency'
remote:        /tmp/build_7d1bb159f39028a7b61479242a948632/vendor/bundle/ruby/2.0.0/gems/activesupport-4.0.4/lib/active_support/dependencies.rb:229:in `require'
remote:        /tmp/build_7d1bb159f39028a7b61479242a948632/vendor/bundle/ruby/2.0.0/gems/railties-4.0.4/lib/rails/application.rb:189:in `require_environment!'
remote:        /tmp/build_7d1bb159f39028a7b61479242a948632/vendor/bundle/ruby/2.0.0/gems/railties-4.0.4/lib/rails/application.rb:250:in `block in run_tasks_blocks'
remote:        /tmp/build_7d1bb159f39028a7b61479242a948632/vendor/bundle/ruby/2.0.0/gems/sprockets-rails-2.0.1/lib/sprockets/rails/task.rb:54:in `block (2 levels) in define'
remote:        Tasks: TOP => environment
remote:        (See full trace by running task with --trace)
remote:  !
remote:  !     Precompiling assets failed.
remote:  !
remote: 
remote:  !     Push rejected, failed to compile Ruby app
remote: 
remote: Verifying deploy....
remote: 
remote: !	Push rejected to app.
remote: 
```

A related question on Stackoverflow shows the same error and fix by reverting to SSH authentication, but without a problem explanation.
http://stackoverflow.com/questions/27366487/heroku-argumenterror-invalid-url-maybe-incompatible-with-redis

Any suggestions on this?

**Comment by dickeyxxx** [comment]
cc @jsimone

**Comment by jsimone** [comment]
@tt @ryanbrainard what do you guys think?

**Comment by stefan-kolb** [comment]
Further infos:
This workflow succeds: https://github.com/stefan-kolb/paasyard/blob/695149fe79480fcf2c761a9bdc471003d18ce4d5/provider/heroku/deploy
While this one fails:
https://github.com/stefan-kolb/paasyard/blob/c2de330ed42ce0dd274fb5b0b3a857b16f60b3e3/provider/heroku/deploy

I haven't changed any of my application code. It's Rails 4.0.5, Redis 3.0.6, sprockets-rails 2.0.1

Hopefully I'm not into some dumb mistakes.

**Comment by tt** [comment]
I proposed a fix in heroku/codon#355.

**Comment by dickeyxxx** [comment]
@tt is this live?

**Comment by tt** [comment]
It is!

**Comment by stefan-kolb** [comment]
I also did a test, should work, thanks!
