### ISSUE TITLE
Can't deploy to heroku via CircleCI as of 26 mins ago

### ISSUE THREAD

**Issue by alantrrs** [heroku/heroku#1441]
Failing with the following error:
```
error: Could not remove config section 'remote.heroku'
Git remote heroku added
updating... !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       Update hash signature mismatch (Heroku::Command::CommandFailed)
    Backtrace:   /usr/local/heroku/lib/heroku/updater.rb:9:in `error'
                 /usr/local/heroku/lib/heroku/updater.rb:117:in `block (2 levels) in update'
                 /home/ubuntu/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/tmpdir.rb:83:in `mktmpdir'
                 /usr/local/heroku/lib/heroku/updater.rb:106:in `block in update'
                 /usr/local/heroku/lib/heroku/updater.rb:83:in `wait_for_lock'
                 /usr/local/heroku/lib/heroku/updater.rb:102:in `update'
                 /usr/local/heroku/lib/heroku/updater.rb:95:in `autoupdate'
                 /usr/local/heroku/lib/heroku/cli.rb:40:in `start'
                 /usr/local/heroku/bin/heroku:74:in `<main>'

    Command:     heroku git:remote --ssh-git -a fuiszmedia-production
```

**Comment by alantrrs** [comment]
When trying to deploy from my local (skipping circle) I get this:
```
remote: Using release configuration from last framework (ffmpeg).
remote: -----> Discovering process types
remote:        Procfile declares types -> tag_saver, web
remote: 
remote: -----> Compressing... done, 94.2MB
remote: -----> Launching... done, v49
remote:        https://fuiszmedia-beta.herokuapp.com/ deployed to Heroku
remote: 
remote: Verifying deploy... done.
fatal: protocol error: bad line length character: erro
error: error in sideband demultiplexer
```

**Comment by dickeyxxx** [comment]
is this still happening? I pushed out a fix for it

**Comment by alantrrs** [comment]
Nope, Seems fixed thanks!
