### ISSUE TITLE
Error running `heroku pg:backups capture --app APP_NAME`

### ISSUE THREAD

**Issue by aaroncraigongithub** [heroku/heroku#1449]
When I run:

```
heroku pg:backups capture --app APP_NAME
```

I see:

```
HEROKU_POSTGRESQL_IVORY ---backup---> b002

 !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       undefined method `transfers_get' for #<Heroku::Client::HerokuPostgresql:0x000001008b83e0> (NoMethodError)
    Command:     heroku pg:backups capture --app live-content-ops
    Plugins:     heroku-accounts
                 heroku-pg-extras
                 heroku-repo

    Version:     heroku-toolbelt/3.28.6 (x86_64-darwin10.8.0) ruby/1.9.3
    Error ID:    b8ffdd157bc149ad84b0055b730c66aa
```

error.log output:
```
Heroku client internal error.
undefined method `transfers_get' for #<Heroku::Client::HerokuPostgresql:0x000001010535c8>
/Users/aaron/.heroku/plugins/heroku-pg-extras/lib/heroku/command/pg_backups.rb:290:in `poll_transfer'
/Users/aaron/.heroku/plugins/heroku-pg-extras/lib/heroku/command/pg_backups.rb:236:in `capture_backup'
/Users/aaron/.heroku/plugins/heroku-pg-extras/lib/heroku/command/pg_backups.rb:50:in `backups'
/Users/aaron/.heroku/client/lib/heroku/command.rb:223:in `run'
/Users/aaron/.heroku/client/lib/heroku/cli.rb:40:in `start'
/usr/local/heroku/bin/heroku:24:in `<main>'
```

This is on OSX 10.10.2

**Comment by dickeyxxx** [comment]
try updating your plugins

**Comment by aaroncraigongithub** [comment]
Awesome, that works.

I assumed the when heroku says it automatically stays updated, that included plugins as well.

Thanks for the quick response.
