### ISSUE TITLE
heroku certs:info failing

### ISSUE THREAD

**Issue by altfatterz** [heroku/heroku#1565]
```
➜  mongodb-compose git:(master) heroku certs:info
Fetching SSL Endpoint mongodb-compose.herokuapp.com info for mongodb-compose... done
Certificate details:
 !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       undefined method `[]' for nil:NilClass (NoMethodError)
    Command:     heroku certs:info
    Plugins:     heroku-pipeline
    Version:     heroku-toolbelt/3.36.6 (x86_64-darwin10.8.0) ruby/1.9.3
    Error ID:    cbe2191bd71743a896d1d1b1da6e5bd7


    More information in /Users/Zoltan/.heroku/error.log

```

**Comment by dickeyxxx** [comment]
can you run this again like so

```
HEROKU_DEBUG=true heroku certs:info
```

and remove any sensitive information you see in the output. If you'd like, you can submit a support ticket instead.

**Comment by altfatterz** [comment]
I don't get more information with `HEROKU_DEBUG=true`

```
➜  mongodb-compose git:(master) ✗ HEROKU_DEBUG=true heroku certs:info
Fetching SSL Endpoint mongodb-compose.herokuapp.com info for mongodb-compose... done
Certificate details:
 !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       undefined method `[]' for nil:NilClass (NoMethodError)
    Command:     heroku certs:info
    Plugins:     heroku-pipeline
    Version:     heroku-toolbelt/3.36.6 (x86_64-darwin10.8.0) ruby/1.9.3
    Error ID:    8ee400ee8e1d407185b23eb03b51c701


    More information in /Users/Zoltan/.heroku/error.log
```
in the logs I see

```
Heroku client internal error.
undefined method `[]' for nil:NilClass
/Users/Zoltan/.heroku/client/lib/heroku/command/certs.rb:204:in `display_certificate_info'
/Users/Zoltan/.heroku/client/lib/heroku/command/certs.rb:119:in `info'
/Users/Zoltan/.heroku/client/lib/heroku/command.rb:212:in `run'
/Users/Zoltan/.heroku/client/lib/heroku/cli.rb:27:in `start'
/usr/local/heroku/bin/heroku:24:in `<main>'
```

**Comment by dickeyxxx** [comment]
ah it must be under restclient then

try

```
RESTCLIENT_LOG=stdout heroku certs:info
```

**Comment by altfatterz** [comment]
I don't see the error anymore after the automatic update of heroku toolbelt to 3.36.7

**Comment by dickeyxxx** [comment]
that didn't fix it @heroku/api I think there is something going on with this call, this isn't the first issue I've seen with it

**Comment by brandur** [comment]
@altfatterz @dickeyxxx Ugh, we had a small problem in the last couple weeks with a certificate cleaner that was being overly aggressive. We finalized a fix today and it was shipped out about two hours ago.

It looks like the endpoint on this app has since been deleted so it's hard to confirm that it was indeed the issue here, but I suspect that if you try this again you won't run into the same problem this time.

/cc @watsonian

**Comment by dickeyxxx** [comment]
glad to hear it's fixed!

**Comment by TheNaoX** [comment]
Hey I'm having the issue now.

**Comment by we5** [comment]
I have this too while adding new certificates

**Comment by dickeyxxx** [comment]
Please submit a support ticket for issues like this. This project is for the CLI only.
