### ISSUE TITLE
`heroku pg:backups schedules` blows up with no databases

### ISSUE THREAD

**Issue by csuhta** [heroku/heroku#1587]
`heroku pg:backups schedules` errors out when you don't have any databases.

```
$ heroku apps:create 
Creating pure-lowlands-1806... done, stack is cedar-14
https://pure-lowlands-1806.herokuapp.com/ | https://git.heroku.com/pure-lowlands-1806.git

$ heroku pg:backups schedules --app pure-lowlands-1806
 !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       undefined method `resource_name' for nil:NilClass (NoMethodError)
    Command:     heroku pg:backups schedules --app pure-lowlands-1806
    Plugins:     heroku-repo
    Version:     heroku-toolbelt/3.37.1 (x86_64-darwin10.8.0) ruby/1.9.3
    Error ID:    61c7326918844c27b342818bf7087417


    More information in /Users/Csuhta/.heroku/error.log


$ heroku version
heroku-toolbelt/3.37.1 (x86_64-darwin10.8.0) ruby/1.9.3
heroku-cli/4.19.27-2964e9b (amd64-darwin) go1.4.2
=== Installed Plugins
heroku-apps@0.1.4
heroku-fork@3.0.4
heroku-repo
```

From the log:

```
Heroku client internal error.
undefined method `resource_name' for nil:NilClass
/Users/Csuhta/.heroku/client/lib/heroku/client/heroku_postgresql.rb:36:in `resource_name'
/Users/Csuhta/.heroku/client/lib/heroku/client/heroku_postgresql.rb:132:in `schedules'
/Users/Csuhta/.heroku/client/lib/heroku/command/pg_backups.rb:558:in `list_schedules'
/Users/Csuhta/.heroku/client/lib/heroku/command/pg_backups.rb:64:in `backups'
/Users/Csuhta/.heroku/client/lib/heroku/command.rb:212:in `run'
/Users/Csuhta/.heroku/client/lib/heroku/cli.rb:27:in `start'
/usr/local/heroku/bin/heroku:24:in `<main>'
```

**Comment by dickeyxxx** [comment]
@uhoh-itsmaciek have you seen this one?

**Comment by uhoh-itsmaciek** [comment]
I had not, but just added a PR to fix it.

/cc @tef just FYI

**Comment by noortotah** [comment]
I have the same error , how to solve it please ?
