### ISSUE TITLE
Getting NameError on any heroku command

### ISSUE THREAD

**Issue by dsoegijono** [heroku/heroku#1609]
```
$ heroku help
.heroku/client/lib/heroku/helpers.rb:448:in `styled_error': uninitialized constant Heroku::Helpers::Rollbar (NameError)
	from /usr/local/heroku/lib/heroku/cli.rb:33:in `rescue in start'
	from /usr/local/heroku/lib/heroku/cli.rb:19:in `start'
	from /usr/bin/heroku:24:in `<main>'
```

No idea why or when the error started, but it was working fine previously, no upgrades or anything, but any `heroku` command is now not working (always same error). Can someone help point me to the direction for a fix please?

**Comment by dsoegijono** [comment]
Still no clue what happened but uninstalling and reinstalling heroku toolbelt (mac) "fixed" it
