### ISSUE TITLE
Error:       An existing connection was forcibly closed by the remote host. (Errno::ECONNRESET) (Excon::Errors::SocketError)

### ISSUE THREAD

**Issue by zongwan** [heroku/heroku#1620]
```
λ  heroku create
Creating agile-anchorage-9959... done, stack is cedar-14
https://agile-anchorage-9959.herokuapp.com/ | https://git.heroku.com/agile-anchorage-9959.git
Git remote heroku added
updating Heroku CLI... !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       An existing connection was forcibly closed by the remote host. (Errno::ECONNRESET) (Excon::Errors::SocketError)
    Command:     heroku create
    Version:     heroku/toolbelt/3.37.7 (i386-mingw32) ruby/1.9.3
    Error ID:    b0a9d6e294124ec08ad6c56c6576ae10


    More information in C:/Users/hou/.heroku/error.log
```

```
λ cat C:\Users\hou\.heroku\error.log
Heroku client internal error.
An existing connection was forcibly closed by the remote host. (Errno::ECONNRESE T)
C:/Program Files (x86)/Heroku/vendor/gems/excon-0.45.2/lib/excon/socket.rb:45:in  `read_nonblock'
C:/Program Files (x86)/Heroku/vendor/gems/excon-0.45.2/lib/excon/socket.rb:45:in  `readline'
C:/Program Files (x86)/Heroku/vendor/gems/excon-0.45.2/lib/excon/response.rb:53: in `parse'
C:/Program Files (x86)/Heroku/vendor/gems/excon-0.45.2/lib/excon/middlewares/res ponse_parser.rb:6:in `response_call'
C:/Program Files (x86)/Heroku/vendor/gems/excon-0.45.2/lib/excon/connection.rb:3 72:in `response'
C:/Program Files (x86)/Heroku/vendor/gems/excon-0.45.2/lib/excon/connection.rb:2 36:in `request'
C:/Program Files (x86)/Heroku/vendor/gems/excon-0.45.2/lib/excon.rb:229:in `get' C:/Program Files (x86)/Heroku/lib/heroku/excon.rb:4:in `get_with_redirect'
C:/Program Files (x86)/Heroku/lib/heroku/excon.rb:6:in `get_with_redirect'
C:/Program Files (x86)/Heroku/lib/heroku/updater.rb:36:in `http_get'
C:/Program Files (x86)/Heroku/lib/heroku/updater.rb:150:in `block in download_fi le'
C:/Program Files (x86)/Heroku/lib/heroku/updater.rb:149:in `open'
C:/Program Files (x86)/Heroku/lib/heroku/updater.rb:149:in `download_file'
C:/Program Files (x86)/Heroku/lib/heroku/updater.rb:124:in `block (2 levels) in
update'
C:/Program Files (x86)/Heroku/ruby-1.9.3/lib/ruby/1.9.1/tmpdir.rb:83:in `mktmpdi r'
C:/Program Files (x86)/Heroku/lib/heroku/updater.rb:116:in `block in update'
C:/Program Files (x86)/Heroku/lib/heroku/updater.rb:88:in `wait_for_lock'
C:/Program Files (x86)/Heroku/lib/heroku/updater.rb:112:in `update'
C:/Program Files (x86)/Heroku/lib/heroku/updater.rb:101:in `autoupdate'
C:/Program Files (x86)/Heroku/lib/heroku/cli.rb:28:in `start'
C:/Program Files (x86)/Heroku/bin/heroku:29:in `<main>'
```

**Comment by zongwan** [comment]
Environment
```
os: win8.1
terminal : cmder
```

**Comment by zongwan** [comment]
```
git clone https://github.com/heroku/python-getting-started.git --depth=1
```

because of "--depth=1"
