### ISSUE TITLE
Heroku plugins install crashes on windows

### ISSUE THREAD

**Issue by trikadin** [heroku/heroku#1630]
```
> heroku plugins:install heroku-apps
Installing plugin heroku-apps...  ▸    module.js:334
 ▸        throw err;
 ▸              ^
 ▸    Error: Cannot find module 'npmlog'
 ▸        at Function.Module._resolveFilename (module.js:332:15)
 ▸        at Function.Module._load (module.js:282:25)
 ▸        at Module.require (module.js:361:17)
 ▸        at require (module.js:380:17)
 ▸        at C:\Users\Константин\.heroku\iojs-v2.2.1-windows-ia32\lib\node_modules\npm\bin\npm-cli.js:18:11
 ▸        at Object.<anonymous> (C:\Users\Константин\.heroku\iojs-v2.2.1-windows-ia32\lib\node_modules\npm\bin\npm-cli.js:75:3)
 ▸        at Module._compile (module.js:426:26)
 ▸        at Object.Module._extensions..js (module.js:444:10)
 ▸        at Module.load (module.js:351:32)
 ▸        at Function.Module._load (module.js:306:12)
```
Windows 8.1

**Comment by dickeyxxx** [comment]
do you have anything in your npmrc file?

**Comment by trikadin** [comment]
As i see, I even don't have a npmrc file in my home directory.

Or I don't understand what npmrc file you're talking about.

**Comment by dickeyxxx** [comment]
maybe try deleting `~/.heroku` then. It seems npm only partially installed.

**Comment by trikadin** [comment]
Already tried to reinstall heroku. I deleted  ~/.heroku too.

**Comment by dickeyxxx** [comment]
can you update then run this again with `GODE_DEBUG=1`?
