### ISSUE TITLE
Error when updating CLI

### ISSUE THREAD

**Issue by leighhalliday** [heroku/heroku#1636]
```
➜  tdtreedays_rails git:(master) heroku run rails c --app tdtreedays
updating v4 CLI to 4.20.8-96504ec (master)... panic: open /Users/lhalliday/.heroku/heroku-cli.new: no such file or directory

goroutine 7 [running]:
main.fileSha1(0xc2081d8060, 0x27, 0x0, 0x0)
	/Users/jdickey/src/github.com/heroku/heroku-cli/update.go:256 +0xbf
main.updateCLI(0x4187b0, 0x6)
	/Users/jdickey/src/github.com/heroku/heroku-cli/update.go:171 +0x635
main.func·014()
	/Users/jdickey/src/github.com/heroku/heroku-cli/update.go:103 +0x4f
created by main.Update
	/Users/jdickey/src/github.com/heroku/heroku-cli/update.go:106 +0x18e

goroutine 1 [select]:
main.Update(0x4187b0, 0x6, 0x37bcf0, 0x5)
	/Users/jdickey/src/github.com/heroku/heroku-cli/update.go:107 +0x32e
main.main()
	/Users/jdickey/src/github.com/heroku/heroku-cli/main.go:52 +0x63

goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/Cellar/go/1.4.2/libexec/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/local/Cellar/go/1.4.2/libexec/src/os/signal/signal_unix.go:27 +0x35

goroutine 6 [chan receive]:
github.com/stvp/rollbar.func·001()
	/Users/jdickey/src/github.com/stvp/rollbar/rollbar.go:74 +0x53
created by github.com/stvp/rollbar.init·1
	/Users/jdickey/src/github.com/stvp/rollbar/rollbar.go:78 +0x5f

goroutine 12 [IO wait]:
net.(*pollDesc).Wait(0xc2081f0d80, 0x72, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2081f0d80, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc2081f0d20, 0xc208240000, 0x8000, 0x8000, 0x0, 0x1911bb8, 0xc2081d38d8)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc208032070, 0xc208240000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/net.go:121 +0xdc
crypto/tls.(*block).readFromUntil(0xc20813ee70, 0x1917598, 0xc208032070, 0x5, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/crypto/tls/conn.go:454 +0xe6
crypto/tls.(*Conn).readRecord(0xc208101080, 0x17, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/crypto/tls/conn.go:539 +0x2da
crypto/tls.(*Conn).Read(0xc208101080, 0xc2081ab000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/crypto/tls/conn.go:904 +0x166
net/http.noteEOFReader.Read(0x1917998, 0xc208101080, 0xc2080c7448, 0xc2081ab000, 0x1000, 0x1000, 0x2dbc80, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/transport.go:1270 +0x6e
net/http.(*noteEOFReader).Read(0xc2081bc000, 0xc2081ab000, 0x1000, 0x1000, 0xc208012000, 0x0, 0x0)
	<autogenerated>:125 +0xd4
bufio.(*Reader).fill(0xc208220120)
	/usr/local/Cellar/go/1.4.2/libexec/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Peek(0xc208220120, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/bufio/bufio.go:132 +0xf0
net/http.(*persistConn).readLoop(0xc2080c73f0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/transport.go:842 +0xa4
created by net/http.(*Transport).dialConn
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/transport.go:660 +0xc9f

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/asm_amd64.s:2232 +0x1

goroutine 13 [select]:
net/http.(*persistConn).writeLoop(0xc2080c73f0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/transport.go:661 +0xcbc
error loading plugin commands
Running `rails c` attached to terminal... up, run.4199
/app/vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.10/lib/action_dispatch/http/mime_type.rb:163: warning: already initialized constant Mime::HTML
/app/vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.10/lib/action_dispatch/http/mime_type.rb:163: warning: previous definition of HTML was here
Loading production environment (Rails 4.1.10)
irb(main):001:0> 
```

**Comment by dickeyxxx** [comment]
did this just happen once or do you see it every time?

**Comment by leighhalliday** [comment]
Hi Jeff,
Just once. When it did the upgrade to the latest version of the CLI.

Thanks,
Leigh

**Comment by dickeyxxx** [comment]
you wouldn't happen to know how long it has been since it had updated previously? This might've been a bug that was resolved.

**Comment by leighhalliday** [comment]
Sorry Jeff... I'm not sure!!

**Comment by dickeyxxx** [comment]
no problem, I'm going to close assuming this was something I resolved previously. Let me know if you see this pop up again!

**Comment by muescha** [comment]
i have the same error today (maybe `heroku` is used from me last time 26 oct 2015 - but i'm not shure if i used it on an other mac)

```
$ heroku ps
Updating Heroku v4 CLI to 4.27.9-cce0260 (master)... panic: open /Users/muescha/.heroku/heroku-cli.new: no such file or directory

goroutine 7 [running]:
main.fileSha1(0xc82036c420, 0x25, 0x0, 0x0)
	/Users/jdickey/src/github.com/heroku/heroku-cli/update.go:210 +0xb8
main.updateCLI(0x47f1d0, 0x6)
	/Users/jdickey/src/github.com/heroku/heroku-cli/update.go:126 +0x52d
main.Update.func1(0x47f1d0, 0x6, 0x3e2ac8, 0x5, 0xc8203125a0)
	/Users/jdickey/src/github.com/heroku/heroku-cli/update.go:61 +0x30
created by main.Update
	/Users/jdickey/src/github.com/heroku/heroku-cli/update.go:65 +0x1d0

goroutine 1 [select]:
main.Update(0x47f1d0, 0x6, 0x3e2ac8, 0x5)
	/Users/jdickey/src/github.com/heroku/heroku-cli/update.go:66 +0x383
main.main()
	/Users/jdickey/src/github.com/heroku/heroku-cli/main.go:74 +0x76

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/Cellar/go/1.5.1/libexec/src/runtime/asm_amd64.s:1696 +0x1

goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/Cellar/go/1.5.1/libexec/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/Cellar/go/1.5.1/libexec/src/os/signal/signal_unix.go:28 +0x37

goroutine 6 [chan receive]:
github.com/stvp/rollbar.init.1.func1()
	/Users/jdickey/src/github.com/stvp/rollbar/rollbar.go:74 +0x4c
created by github.com/stvp/rollbar.init.1
	/Users/jdickey/src/github.com/stvp/rollbar/rollbar.go:78 +0x5c

goroutine 12 [IO wait]:
net.runtime_pollWait(0x6cc080, 0x72, 0xc820010160)
	/usr/local/Cellar/go/1.5.1/libexec/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8202bd560, 0x72, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.1/libexec/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8202bd560, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.1/libexec/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8202bd500, 0xc820394000, 0x8000, 0x8000, 0x0, 0x6be050, 0xc820010160)
	/usr/local/Cellar/go/1.5.1/libexec/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc820030070, 0xc820394000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.1/libexec/src/net/net.go:172 +0xe4
crypto/tls.(*block).readFromUntil(0xc820342b10, 0x6cc190, 0xc820030070, 0x5, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.1/libexec/src/crypto/tls/conn.go:455 +0xcc
crypto/tls.(*Conn).readRecord(0xc820117600, 0x47fe17, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.1/libexec/src/crypto/tls/conn.go:540 +0x2d1
crypto/tls.(*Conn).Read(0xc820117600, 0xc820355000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.1/libexec/src/crypto/tls/conn.go:901 +0x167
net/http.noteEOFReader.Read(0x6cc568, 0xc820117600, 0xc82033e1b8, 0xc820355000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.1/libexec/src/net/http/transport.go:1370 +0x67
net/http.(*noteEOFReader).Read(0xc820360a60, 0xc820355000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	<autogenerated>:126 +0xd0
bufio.(*Reader).fill(0xc820313140)
	/usr/local/Cellar/go/1.5.1/libexec/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc820313140, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.1/libexec/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc82033e160)
	/usr/local/Cellar/go/1.5.1/libexec/src/net/http/transport.go:876 +0xf7
created by net/http.(*Transport).dialConn
	/usr/local/Cellar/go/1.5.1/libexec/src/net/http/transport.go:685 +0xc78

goroutine 13 [select]:
net/http.(*persistConn).writeLoop(0xc82033e160)
	/usr/local/Cellar/go/1.5.1/libexec/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
	/usr/local/Cellar/go/1.5.1/libexec/src/net/http/transport.go:686 +0xc9d
 !    error getting commands pid 1561 exit 2
[07:09:39] muescha@MacBook-Pro:~ 
$ heroku ps
 ▸    No app specified.
 ▸    Run this command from an app folder or specify which app to use with --app APP
[07:11:29] muescha@MacBook-Pro:~ 
```


PS:
i am just confused about this lines in error log `/Users/jdickey/src/github.com/heroku/...` because `jdickey` not an user at my mac

**Comment by dickeyxxx** [comment]
if you delete `/Users/muescha/.heroku` it should fix any issues you might still be having. It shows that path because Go's tracebacks show the path to where the files were originally compiled (my machine).

**Comment by muescha** [comment]
i forget to mention: a second run of `heroku` comes without error


PS: thats confusing with the GO's tracebacks :(

**Comment by zaverichintan** [comment]
I am not getting any errors log just 
C:\Users\Chintan>heroku
panic:
