### ISSUE TITLE
Heroku client internal error

### ISSUE THREAD

**Issue by devangmundhra** [heroku/heroku#1642]
```
updating Heroku CLI... !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       Update hash signature mismatch (Heroku::Command::CommandFailed)
    Command:     heroku run python manage.py migrate
    Version:     heroku-toolbelt/3.38.1 (x86_64-darwin10.8.0) ruby/1.9.3
    Error ID:    79556822e81443caae3395a49855daab


    More information in /Users/devm/.heroku/error.log
```

On looking into the error.log file, the error is-

```
Heroku client internal error.
Update hash signature mismatch
/Users/devm/.heroku/client/lib/heroku/updater.rb:10:in `error'
/Users/devm/.heroku/client/lib/heroku/updater.rb:127:in `block (2 levels) in update'
/usr/local/heroku/ruby/lib/ruby/1.9.1/tmpdir.rb:83:in `mktmpdir'
/Users/devm/.heroku/client/lib/heroku/updater.rb:116:in `block in update'
/Users/devm/.heroku/client/lib/heroku/updater.rb:88:in `wait_for_lock'
/Users/devm/.heroku/client/lib/heroku/updater.rb:112:in `update'
/Users/devm/.heroku/client/lib/heroku/updater.rb:101:in `autoupdate'
/Users/devm/.heroku/client/lib/heroku/cli.rb:28:in `start'
/usr/bin/heroku:24:in `<main>'

```

I have upgraded my `Ruby` version to 2.2 on my machine, but is it because from the error trace above-
`/usr/local/heroku/ruby/lib/ruby/1.9.1/tmpdir.rb:83:in mktmpdir`, heroku is still using `ruby v1.9.1`? If so, how do I fix it?

I also tried `rm -rf ~/.heroku` but get this error on update-

```
$ heroku update
updating... !    Update hash signature mismatch
```

**Comment by gautamchandna** [comment]
Same for me, and I'm on Windows. Could this have returned https://github.com/heroku/heroku/issues/1098 ?

**Comment by dickeyxxx** [comment]
this is now resolved
