### ISSUE TITLE
heroku pg:diagnose "psql: SSL error: point is not on curve"

### ISSUE THREAD

**Issue by jeffblake** [heroku/heroku#1664]
psql: SSL error: point is not on curve

 !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       psql failed. exit status 512, output: "" (RuntimeError)
    Command:     heroku pg:diagnose -r production
    Plugins:     heroku-pg-extras
                 heroku-repo

    Version:     heroku-toolbelt/3.39.5 (x86_64-darwin10.8.0) ruby/1.9.3
    Error ID:    76f47123af7f4dfc8922a97826ece2f2

Heroku client internal error.
psql failed. exit status 512, output: ""
/Users/jblake/.heroku/client/lib/heroku/command/pg.rb:783:in `exec_sql_on_uri'
/Users/jblake/.heroku/client/lib/heroku/command/pg.rb:772:in `exec_sql'
/Users/jblake/.heroku/client/lib/heroku/command/pg.rb:744:in `version'
/Users/jblake/.heroku/client/lib/heroku/command/pg.rb:751:in `nine_two?'
/Users/jblake/.heroku/client/lib/heroku/helpers/pg_diagnose.rb:65:in `warn_old_databases'
/Users/jblake/.heroku/client/lib/heroku/helpers/pg_diagnose.rb:45:in `generate_report'
/Users/jblake/.heroku/client/lib/heroku/helpers/pg_diagnose.rb:23:in `find_or_generate_report'
/Users/jblake/.heroku/client/lib/heroku/helpers/pg_diagnose.rb:6:in `run_diagnose'
/Users/jblake/.heroku/client/lib/heroku/command/pg.rb:74:in `diagnose'
/Users/jblake/.heroku/client/lib/heroku/command.rb:212:in `run'
/Users/jblake/.heroku/client/lib/heroku/cli.rb:27:in `start'
/usr/local/heroku/bin/heroku:24:in `<main>'

**Comment by jeffblake** [comment]
Upgrading PostgresApp (http://postgresapp.com/) fixed the problem.
