### ISSUE TITLE
Error for "heroku pg:psql", here is the log for "heroku pg:diagnose"

### ISSUE THREAD

**Issue by brian-writes-code** [heroku/heroku#1669]
I've been trying to access a remote heroku-postgres database, but it always give me this error: 

---> Connecting to HEROKU_POSTGRESQL_ORANGE_URL (DATABASE_URL)
psql: could not connect to server: Connection refused
	Is the server running on host "ec2-***-**-***-**.compute-1.amazonaws.com" (***.**.***.**) and accepting
	TCP/IP connections on port 5432?

Here is the output I get when running heroku pg:diagnose.

```
    Error:       psql failed. exit status 512, output: "" (RuntimeError)
    Command:     heroku pg:diagnose
    Version:     heroku-toolbelt/3.40.6 (x86_64-linux) ruby/1.9.3
    Error ID:    21155f102b0f415a838e5be9d6f61455


    More information in /home/brian/.heroku/error.log
```
____________________________________________________
 /home/brian/.heroku/error.log:

2015/07/23 00:31:59 setting up iojs 2.3.3
2015/07/23 00:32:15 done setting up iojs
2015/07/23 00:32:15 Installing plugin heroku-git... 
2015/07/23 00:32:21 done
2015/07/23 23:08:49 updating plugins... 
2015/07/23 23:08:50 done
Heroku client internal error.
psql failed. exit status 512, output: ""
/usr/local/heroku/lib/heroku/command/pg.rb:783:in `exec_sql_on_uri'
/usr/local/heroku/lib/heroku/command/pg.rb:772:in `exec_sql'
/usr/local/heroku/lib/heroku/command/pg.rb:744:in `version'
/usr/local/heroku/lib/heroku/command/pg.rb:751:in `nine_two?'
/usr/local/heroku/lib/heroku/helpers/pg_diagnose.rb:65:in `warn_old_databases'
/usr/local/heroku/lib/heroku/helpers/pg_diagnose.rb:45:in `generate_report'
/usr/local/heroku/lib/heroku/helpers/pg_diagnose.rb:23:in `find_or_generate_report'
/usr/local/heroku/lib/heroku/helpers/pg_diagnose.rb:6:in `run_diagnose'
/usr/local/heroku/lib/heroku/command/pg.rb:74:in `diagnose'
/usr/local/heroku/lib/heroku/command.rb:212:in `run'
/usr/local/heroku/lib/heroku/cli.rb:27:in `start'
/usr/local/heroku/bin/heroku:25:in `<main>'

**Comment by dickeyxxx** [comment]
does `psql` work?

**Comment by brian-writes-code** [comment]
That was the command I originally wanted to get working as I need to change my remote database locally from my computer.

Very strangely, heroku pg:psql only works during certain times during the day.  Is this supposed to happen??

**Comment by dickeyxxx** [comment]
if `psql` isn't working then that means something is wrong with your local install of postgres

**Comment by brian-writes-code** [comment]
Postgres seems to be working locally.  I am just quite confused why heroku pg:psql simply gives me this error:
    psql: could not connect to server: Connection refused
    Is the server running on host "ec2-**---.compute-1.amazonaws.com" (**...) and accepting
    TCP/IP connections on port 5432?
at night, eastern time.  During the day, I am able to enter the remote Postgres shell.

**Comment by brian-writes-code** [comment]
Sorry, just the command "psql" works.

**Comment by dickeyxxx** [comment]
you should submit a support ticket, this doesn't look like an issue with the CLI
