### ISSUE TITLE
Windows 10 lacks crtdll

### ISSUE THREAD

**Issue by chernetsov0** [heroku/heroku#1696]
It leads to following stack trace after entering email on login:

```
Password (typing will be hidden): <ruby_install_dir>/lib/ruby/2.0.0/Win32API.rb:14:in `initialize': No such file or directory (LoadError)
    from <ruby_install_dir>/lib/ruby/2.0.0/Win32API.rb:14:in `dlopen'
    from <ruby_install_dir>/lib/ruby/2.0.0/Win32API.rb:14:in `initialize'
    from <ruby_install_dir>/lib/ruby/gems/2.0.0/gems/heroku-3.41.3/lib/heroku/auth.rb:245:in `new'
    from <ruby_install_dir>/lib/ruby/gems/2.0.0/gems/heroku-3.41.3/lib/heroku/auth.rb:245:in `ask_for_password_on_windows'
    from <ruby_install_dir>/lib/ruby/gems/2.0.0/gems/heroku-3.41.3/lib/heroku/auth.rb:220:in `ask_for_credentials'
    from <ruby_install_dir>/lib/ruby/gems/2.0.0/gems/heroku-3.41.3/lib/heroku/auth.rb:271:in `ask_for_and_save_credentials'
    from <ruby_install_dir>/lib/ruby/gems/2.0.0/gems/heroku-3.41.3/lib/heroku/auth.rb:111:in `get_credentials'
    from <ruby_install_dir>/lib/ruby/gems/2.0.0/gems/heroku-3.41.3/lib/heroku/auth.rb:46:in `login'
    from <ruby_install_dir>/lib/ruby/gems/2.0.0/gems/heroku-3.41.3/lib/heroku/command/auth.rb:31:in `login'
    from <ruby_install_dir>/lib/ruby/gems/2.0.0/gems/heroku-3.41.3/lib/heroku/command.rb:212:in `run'
    from <ruby_install_dir>/lib/ruby/gems/2.0.0/gems/heroku-3.41.3/lib/heroku/cli.rb:27:in `start'
    from <ruby_install_dir>/lib/ruby/gems/2.0.0/gems/heroku-3.41.3/bin/heroku:17:in `<top (required)>'
    from <ruby_install_dir>/bin/heroku:23:in `load'
    from <ruby_install_dir>/bin/heroku:23:in `<main>'
```

One of the solutions is to use `msvcrt` [here](https://github.com/heroku/heroku/blob/v3.41.3/lib/heroku/auth.rb#L245) but it needs to be tested on older versions of windows.

**Comment by chidumaga** [comment]
See <a href="https://github.com/heroku/heroku/issues/1686">1686</a>. Running Windows 7(x64).

**Comment by chernetsov0** [comment]
If everyone else has this issue, try replacing `crtdll` with `msvcrt` [here](https://github.com/heroku/heroku/blob/v3.41.3/lib/heroku/auth.rb#L245) and write back whether it works. Will try to do pull request.

@chidumaga can you verify that login still works with this change?

**Comment by S-Aoi** [comment]
@chernetsov0 I have this issue. After replacing it works!
