### ISSUE TITLE
SSL server handshake failure

### ISSUE THREAD

**Issue by niftynei** [heroku/heroku#1761]
I'm having trouble using the heroku cli client.  It's giving me SSL cert errors.

```
♤ 16:29:30 dev heroku update
Updating from 2.31.2... failed
 !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       SSL_connect returned=1 errno=0 state=SSLv3 read server hello A: sslv3 alert handshake failure (OpenSSL::SSL::SSLError) (Excon::Errors::SocketError)
    Backtrace:   /Users/ln/.heroku/client/vendor/gems/excon-0.16.2/lib/excon/ssl_socket.rb:60:in `connect'
                 /Users/ln/.heroku/client/vendor/gems/excon-0.16.2/lib/excon/ssl_socket.rb:60:in `initialize'
                 /Users/ln/.heroku/client/vendor/gems/excon-0.16.2/lib/excon/connection.rb:357:in `new'
                 /Users/ln/.heroku/client/vendor/gems/excon-0.16.2/lib/excon/connection.rb:357:in `socket'
                 /Users/ln/.heroku/client/vendor/gems/excon-0.16.2/lib/excon/connection.rb:188:in `request_kernel'
                 /Users/ln/.heroku/client/vendor/gems/excon-0.16.2/lib/excon/connection.rb:101:in `request'
                 /Users/ln/.heroku/client/vendor/gems/excon-0.16.2/lib/excon.rb:129:in `head'
                 /Users/ln/.heroku/client/lib/heroku/updater.rb:68:in `block in update'
                 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tmpdir.rb:88:in `mktmpdir'
                 /Users/ln/.heroku/client/lib/heroku/updater.rb:65:in `update'
                 /Users/ln/.heroku/client/lib/heroku/command/update.rb:39:in `block in update_from_url'
                 /Users/ln/.heroku/client/lib/heroku/helpers.rb:232:in `action'
                 /Users/ln/.heroku/client/lib/heroku/command/update.rb:38:in `update_from_url'
                 /Users/ln/.heroku/client/lib/heroku/command/update.rb:19:in `index'
                 /Users/ln/.heroku/client/lib/heroku/command.rb:191:in `run'
                 /Users/ln/.heroku/client/lib/heroku/cli.rb:28:in `start'
                 /usr/bin/heroku:23:in `<main>'

    Command:     heroku update
    Version:     heroku-toolbelt/2.31.2 (universal.x86_64-darwin13) ruby/2.0.0
```

**Comment by dickeyxxx** [comment]
update your toolbelt, your version is very out of date

**Comment by niftynei** [comment]
Updated and fixed. Thanks!

**Comment by katmai** [comment]
i am having the same issue, but eve after updating it says the same thing :


```
[root@SG1 kit]# heroku
Installing Heroku Toolbelt v4... !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: sslv3 alert handshake failure (OpenSSL::SSL::SSLError) (Excon::Errors::SocketError)
    Command:     heroku
    Plugins:     heroku-vim
    Version:     heroku-toolbelt/3.42.17 (x86_64-linux) ruby/1.9.3
    Error ID:    a39631fd17a44f19834c56dd044cdca9


    More information in /root/.heroku/error.log
```
