### ISSUE TITLE
Update hash signature mismatch

### ISSUE THREAD

**Issue by indirect** [heroku/heroku#1770]
Having a bad release day?

```
$ heroku config:set BLAH=foo
Setting config vars and restarting rubytogether-staging... done, v122
/Users/andre/.heroku/client/lib/heroku/updater.rb:10:in `error': Update hash signature mismatch (Heroku::Command::CommandFailed)
        from /Users/andre/.heroku/client/lib/heroku/updater.rb:133:in `block (2 levels) in update'
        from /opt/rubies/2.2.3/lib/ruby/2.2.0/tmpdir.rb:88:in `mktmpdir'
        from /Users/andre/.heroku/client/lib/heroku/updater.rb:122:in `block in update'
        from /Users/andre/.heroku/client/lib/heroku/updater.rb:88:in `wait_for_lock'
        from /Users/andre/.heroku/client/lib/heroku/updater.rb:118:in `update'
        from /Users/andre/.heroku/client/lib/heroku/updater.rb:102:in `block in autoupdate'
        from /Users/andre/.heroku/client/lib/heroku/updater.rb:102:in `fork'
        from /Users/andre/.heroku/client/lib/heroku/updater.rb:102:in `autoupdate'
        from /Users/andre/.heroku/client/lib/heroku/cli.rb:31:in `start'
        from /opt/boxen/heroku/bin/heroku:24:in `<main>'
```

**Comment by dickeyxxx** [comment]
did you get this just now? What OS?
