### ISSUE TITLE
state=SSLv2/v3 read server hello A: sslv3 alert handshake failure

### ISSUE THREAD

**Issue by katmai** [heroku/heroku#1773]
Hi,

since a few days the toolbelt stopped working on my box. Any idea what's up? This is the latest version as far as i can see.

```
[root@SG1 pagzSitesProd]# heroku ps
Installing Heroku Toolbelt v4... !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: sslv3 alert handshake failure (OpenSSL::SSL::SSLError) (Excon::Errors::SocketError)
    Command:     heroku ps
    Plugins:     heroku-vim
    Version:     heroku-toolbelt/3.42.17 (x86_64-linux) ruby/1.9.3
    Error ID:    dfb817cac6014b34b16f2662aca0cb53


    More information in /root/.heroku/error.log
```

```
Heroku client internal error.
SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: sslv3 alert handshake failure (OpenSSL::SSL::SSLError)
/usr/local/heroku/vendor/gems/excon-0.45.4/lib/excon/ssl_socket.rb:120:in `connect_nonblock'
/usr/local/heroku/vendor/gems/excon-0.45.4/lib/excon/ssl_socket.rb:120:in `initialize'
/usr/local/heroku/vendor/gems/excon-0.45.4/lib/excon/connection.rb:387:in `new'
/usr/local/heroku/vendor/gems/excon-0.45.4/lib/excon/connection.rb:387:in `socket'
/usr/local/heroku/vendor/gems/excon-0.45.4/lib/excon/connection.rb:106:in `request_call'
/usr/local/heroku/vendor/gems/excon-0.45.4/lib/excon/middlewares/mock.rb:47:in `request_call'
/usr/local/heroku/vendor/gems/excon-0.45.4/lib/excon/middlewares/instrumentor.rb:22:in `request_call'
/usr/local/heroku/vendor/gems/excon-0.45.4/lib/excon/middlewares/base.rb:15:in `request_call'
/usr/local/heroku/vendor/gems/excon-0.45.4/lib/excon/middlewares/base.rb:15:in `request_call'
/usr/local/heroku/vendor/gems/excon-0.45.4/lib/excon/middlewares/base.rb:15:in `request_call'
/usr/local/heroku/vendor/gems/excon-0.45.4/lib/excon/connection.rb:233:in `request'
/usr/local/heroku/vendor/gems/excon-0.45.4/lib/excon.rb:229:in `get'
/usr/local/heroku/lib/heroku/jsplugin.rb:183:in `manifest'
/usr/local/heroku/lib/heroku/jsplugin.rb:196:in `url'
/usr/local/heroku/lib/heroku/jsplugin.rb:125:in `setup'
/usr/local/heroku/lib/heroku/cli.rb:24:in `start'
/bin/heroku:24:in `<main>'

```

**Comment by dickeyxxx** [comment]
I'm not really sure, but that version of SSL is deprecated and shouldn't be used anymore. Perhaps try reinstalling? What OS is this on?

**Comment by katmai** [comment]
I am running the dev env on centos5 with the default ssl.

**Comment by dickeyxxx** [comment]
Try reinstalling and maybe updating your ruby

**Comment by katmai** [comment]
alright i upgraded to ruby 2.2.3 since i am running it in rvm anyway so it doesn't impact the system and it fixed it:

[root@SG1 ~]# ruby -v
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux]

pretty odd tho, i thought 1.9.3 wasn't that old.

thanks a bunch .

**Comment by dickeyxxx** [comment]
it's not that 1.9.3 is old, it's that you had it compiled against an openssl that has expired ssl algorithms
