### ISSUE TITLE
Cannot run heroku keys:add when Window account name has special character

### ISSUE THREAD

**Issue by seanjb** [heroku/heroku#1778]
Similar to issue #1489 when my User Account folder has a special character... namely: Seán
Running heroku keys:add produces the following error

```
C:/Heroku/ruby-1.9.3/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `
require': cannot load such file -- C:/Users/SeÃ¡n/.heroku/client/vendor/gems/her
oku-api-0.3.23/lib/heroku/api (LoadError)
        from C:/Heroku/ruby-1.9.3/lib/ruby/site_ruby/1.9.1/rubygems/custom_requi
re.rb:36:in `require'
        from C:/Users/Seán/.heroku/client/vendor/gems/heroku-api-0.3.23/lib/hero
ku-api.rb:1:in `<top (required)>'
        from C:/Heroku/ruby-1.9.3/lib/ruby/site_ruby/1.9.1/rubygems/custom_requi
re.rb:36:in `require'
        from C:/Heroku/ruby-1.9.3/lib/ruby/site_ruby/1.9.1/rubygems/custom_requi
re.rb:36:in `require'
        from C:/Users/Seán/.heroku/client/lib/heroku/command.rb:6:in `<top (requ
ired)>'
        from C:/Heroku/ruby-1.9.3/lib/ruby/site_ruby/1.9.1/rubygems/custom_requi
re.rb:36:in `require'
        from C:/Heroku/ruby-1.9.3/lib/ruby/site_ruby/1.9.1/rubygems/custom_requi
re.rb:36:in `require'
        from C:/Users/Seán/.heroku/client/lib/heroku/cli.rb:26:in `start'
        from C:/Heroku/bin/heroku:29:in `<main>'
```

**Comment by dickeyxxx** [comment]
What version of windows? Maybe try reinstalling? I can't reproduce
