### ISSUE TITLE
Panic on Mac OSX

### ISSUE THREAD

**Issue by ryanwjackson** [heroku/heroku#1783]
I get this when running `heroku update`.  If I run it again, it's fine.  Happened twice now (maybe when there's an update?).

```
Updating Heroku v4 CLI to 4.26.1-bf7a4d8 (master)... panic: rename /Users/ryanwjackson/.heroku/heroku-cli.new /Users/ryanwjackson/.heroku/heroku-cli: no such file or directory

goroutine 7 [running]:
main.updateCLI(0x47efd0, 0x6)
	/Users/jdickey/src/github.com/heroku/heroku-cli/update.go:132 +0x706
main.Update.func1(0x47efd0, 0x6, 0x3edbc0, 0xa, 0xc8203125a0)
	/Users/jdickey/src/github.com/heroku/heroku-cli/update.go:61 +0x30
created by main.Update
	/Users/jdickey/src/github.com/heroku/heroku-cli/update.go:65 +0x1d0

goroutine 1 [select]:
main.Update(0x47efd0, 0x6, 0x3edbc0, 0xa)
	/Users/jdickey/src/github.com/heroku/heroku-cli/update.go:66 +0x383
main.glob.func9(0xc82031cb60)
	/Users/jdickey/src/github.com/heroku/heroku-cli/update.go:40 +0x19e
main.(*Cli).Run(0x5b0d20, 0xc82000a360, 0x2, 0x2, 0x0, 0x0)
	/Users/jdickey/src/github.com/heroku/heroku-cli/cli.go:65 +0x5c2
main.main()
	/Users/jdickey/src/github.com/heroku/heroku-cli/main.go:77 +0xb4

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/Cellar/go/1.5.1/libexec/src/runtime/asm_amd64.s:1696 +0x1

goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/Cellar/go/1.5.1/libexec/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/Cellar/go/1.5.1/libexec/src/os/signal/signal_unix.go:28 +0x37

goroutine 6 [chan receive]:
github.com/stvp/rollbar.init.1.func1()
	/Users/jdickey/src/github.com/stvp/rollbar/rollbar.go:74 +0x4c
created by github.com/stvp/rollbar.init.1
	/Users/jdickey/src/github.com/stvp/rollbar/rollbar.go:78 +0x5c

goroutine 12 [IO wait]:
net.runtime_pollWait(0x6caba8, 0x72, 0xc820014160)
	/usr/local/Cellar/go/1.5.1/libexec/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8202bb720, 0x72, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.1/libexec/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8202bb720, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.1/libexec/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8202bb6c0, 0xc820390000, 0x8000, 0x8000, 0x0, 0x6bd050, 0xc820014160)
	/usr/local/Cellar/go/1.5.1/libexec/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc820030080, 0xc820390000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.1/libexec/src/net/net.go:172 +0xe4
crypto/tls.(*block).readFromUntil(0xc82033f2c0, 0x6cacb8, 0xc820030080, 0x5, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.1/libexec/src/crypto/tls/conn.go:455 +0xcc
crypto/tls.(*Conn).readRecord(0xc820119600, 0x47fc17, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.1/libexec/src/crypto/tls/conn.go:540 +0x2d1
crypto/tls.(*Conn).Read(0xc820119600, 0xc820366000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.1/libexec/src/crypto/tls/conn.go:901 +0x167
net/http.noteEOFReader.Read(0x6cb018, 0xc820119600, 0xc8203401b8, 0xc820366000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.1/libexec/src/net/http/transport.go:1370 +0x67
net/http.(*noteEOFReader).Read(0xc82035cee0, 0xc820366000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	<autogenerated>:126 +0xd0
bufio.(*Reader).fill(0xc820313140)
	/usr/local/Cellar/go/1.5.1/libexec/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc820313140, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.1/libexec/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc820340160)
	/usr/local/Cellar/go/1.5.1/libexec/src/net/http/transport.go:876 +0xf7
created by net/http.(*Transport).dialConn
	/usr/local/Cellar/go/1.5.1/libexec/src/net/http/transport.go:685 +0xc78

goroutine 13 [select]:
net/http.(*persistConn).writeLoop(0xc820340160)
	/usr/local/Cellar/go/1.5.1/libexec/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
	/usr/local/Cellar/go/1.5.1/libexec/src/net/http/transport.go:686 +0xc9d
```

**Comment by dickeyxxx** [comment]
maybe just try deleting `~/.heroku`?

**Comment by ryanwjackson** [comment]
I did, let's see if that works.  No real way to tell as I couldn't find a way to reproduce, it just happened on `update` "randomly."  Will post here if it happens again.
