### ISSUE TITLE
All heroku CLI commands fail : Error:       Invalid argument - H: (Errno::EINVAL)

### ISSUE THREAD

**Issue by hichamchraibi** [heroku/heroku#1804]
All heroku CLI commands fail, here is an example with heroku logs : 
2015-11-02T22:37:37.947484+00:00 heroku[api]: Enable Logplex by hicham.chraibi@gmail.com
2015-11-02T22:37:37.947484+00:00 heroku[api]: Release v2 created by hicham.chraibi@gmail.com
2015-11-02T22:39:53.840612+00:00 heroku[api]: Set JAVA_OPTS config vars by hicham.chraibi@gmail.com
2015-11-02T22:39:53.840612+00:00 heroku[api]: Release v3 created by hicham.chraibi@gmail.com
2015-11-02T22:39:54.327004+00:00 heroku[api]: Attach DATABASE resource by hicham.chraibi@gmail.com
2015-11-02T22:39:54.327004+00:00 heroku[api]: Release v4 created by hicham.chraibi@gmail.com
2015-11-02T22:39:54.646920+00:00 heroku[api]: Deploy 1d8b9af by hicham.chraibi@gmail.com
2015-11-02T22:39:54.646920+00:00 heroku[api]: Release v5 created by hicham.chraibi@gmail.com
2015-11-02T22:39:54.961994+00:00 heroku[slug-compiler]: Slug compilation started
2015-11-02T22:39:54.962026+00:00 heroku[slug-compiler]: Slug compilation finished
 !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       Invalid argument - H: (Errno::EINVAL)
    Command:     heroku logs --app calm-anchorage-6151
    Version:     heroku/toolbelt/3.41.5 (i386-mingw32) ruby/1.9.3
    Error ID:    cf5f007eb96d45388fb69590bc136b59

    More information in H:/.heroku/error.log

Invalid argument - H:
C:/Program Files (x86)/Heroku/ruby-1.9.3/lib/ruby/1.9.1/fileutils.rb:247:in `mkdir'
C:/Program Files (x86)/Heroku/ruby-1.9.3/lib/ruby/1.9.1/fileutils.rb:247:in `fu_mkdir'
C:/Program Files (x86)/Heroku/ruby-1.9.3/lib/ruby/1.9.1/fileutils.rb:221:in `block (2 levels) in mkdir_p'
C:/Program Files (x86)/Heroku/ruby-1.9.3/lib/ruby/1.9.1/fileutils.rb:219:in `reverse_each'
C:/Program Files (x86)/Heroku/ruby-1.9.3/lib/ruby/1.9.1/fileutils.rb:219:in `block in mkdir_p'
C:/Program Files (x86)/Heroku/ruby-1.9.3/lib/ruby/1.9.1/fileutils.rb:205:in `each'
C:/Program Files (x86)/Heroku/ruby-1.9.3/lib/ruby/1.9.1/fileutils.rb:205:in `mkdir_p'
C:/Program Files (x86)/Heroku/lib/heroku/helpers.rb:461:in `error_log'
C:/Program Files (x86)/Heroku/lib/heroku/helpers.rb:455:in `styled_error'
C:/Program Files (x86)/Heroku/lib/heroku/cli.rb:39:in `rescue in start'
C:/Program Files (x86)/Heroku/lib/heroku/cli.rb:19:in `start'
C:/Program Files (x86)/Heroku/bin/heroku:29:in `<main>'
Invalid argument - H:
C:/Program Files (x86)/Heroku/ruby-1.9.3/lib/ruby/1.9.1/fileutils.rb:247:in `mkdir'
C:/Program Files (x86)/Heroku/ruby-1.9.3/lib/ruby/1.9.1/fileutils.rb:247:in `fu_mkdir'
C:/Program Files (x86)/Heroku/ruby-1.9.3/lib/ruby/1.9.1/fileutils.rb:221:in `block (2 levels) in mkdir_p'
C:/Program Files (x86)/Heroku/ruby-1.9.3/lib/ruby/1.9.1/fileutils.rb:219:in `reverse_each'
C:/Program Files (x86)/Heroku/ruby-1.9.3/lib/ruby/1.9.1/fileutils.rb:219:in `block in mkdir_p'
C:/Program Files (x86)/Heroku/ruby-1.9.3/lib/ruby/1.9.1/fileutils.rb:205:in `each'
C:/Program Files (x86)/Heroku/ruby-1.9.3/lib/ruby/1.9.1/fileutils.rb:205:in `mkdir_p'
C:/Program Files (x86)/Heroku/lib/heroku/updater.rb:98:in `autoupdate'
C:/Program Files (x86)/Heroku/lib/heroku/cli.rb:28:in `start'
C:/Program Files (x86)/Heroku/bin/heroku:29:in `<main>'

**Comment by dickeyxxx** [comment]
Your home directory is not set properly. Set the `HOME` env var or %USERPROFILE% to a real directory.
