### ISSUE TITLE
singles quote inside double quotes causes an error

### ISSUE THREAD

**Issue by drewB** [heroku/heroku#1806]
suddenly doing commands that include single quotes in double quotes causes an error.  For example:

heroku run "rake blah['joe']"

gives the following error:

[eval]:7
		process.title = 'heroku run rake blah['joe']';
		                                       ^^^

SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:53:16)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:435:26)
    at node.js:576:27
    at doNTCallback0 (node.js:417:9)
    at process._tickCallback (node.js:346:13)

**Comment by dickeyxxx** [comment]
the fix for this is going out right now https://github.com/heroku/heroku-cli/pull/117
