### ISSUE TITLE
Heroku client internal error.

### ISSUE THREAD

**Issue by shoetomydixi** [heroku/heroku#1809]
Error:       bad URI(is not URI?): /apps/z360сonsole-staging/logs?logplex=true&tail=1 (URI::InvalidURIError)
    Command:     heroku logs --tail --app z360сonsole-staging
    Version:     heroku-toolbelt/3.42.21 (x86_64-darwin10.8.0) ruby/1.9.3
    Error ID:    d6da70131bcb4ca09dbae98d47e8bdcb

Heroku client internal error.
bad URI(is not URI?): /apps/z360сonsole-staging/logs?logplex=true&tail=1
/usr/local/heroku/ruby/lib/ruby/1.9.1/uri/common.rb:176:in `split'
/usr/local/heroku/ruby/lib/ruby/1.9.1/uri/common.rb:211:in `parse'
/usr/local/heroku/ruby/lib/ruby/1.9.1/uri/common.rb:747:in `parse'
/Users/deniskashuba/.heroku/client/lib/heroku/client.rb:708:in `realize_full_uri'
/Users/deniskashuba/.heroku/client/lib/heroku/client.rb:719:in `default_resource_options_for_uri'
/Users/deniskashuba/.heroku/client/lib/heroku/client.rb:617:in `process'
/Users/deniskashuba/.heroku/client/lib/heroku/client.rb:598:in `get'
/Users/deniskashuba/.heroku/client/lib/heroku/client.rb:480:in `read_logs'
/Users/deniskashuba/.heroku/client/lib/heroku/helpers/log_displayer.rb:19:in `display_logs'
/Users/deniskashuba/.heroku/client/lib/heroku/command/logs.rb:34:in `index'
/Users/deniskashuba/.heroku/client/lib/heroku/command.rb:212:in `run'
/Users/deniskashuba/.heroku/client/lib/heroku/cli.rb:30:in `start'
/usr/local/bin/heroku:24:in `<main>'

**Comment by dickeyxxx** [comment]
do you have any `HEROKU_*` env vars set?
