### ISSUE TITLE
Error: SHA mismatch for heroku-cli <RuntimeError>

### ISSUE THREAD

**Issue by masdamas** [heroku/heroku#1813]
Please help me to solve this error:

Installing Heroku Toolbelt v4... ! Heroku client internal error.
! Search fot help at: https://help.heroku.com
! Or report a bug at: https://github.com/heroku/heroku/issues/new

  Error:		SHA mismatch for heroku-cli <RuntimeError>
  Command:	heroku login
  Version:		heroku/toolbelt/3.42.20 <i386-mingw32> ruby/1.9.3

  More informastion in c:/Users/Administrator/.heroku/error.log

And this is the error.log:

Heroku client internal error.
SHA mismatch for heroku-cli
C:/Program Files/Heroku/lib/heroku/jsplugin.rb:140:in `setup'
C:/Program Files/Heroku/lib/heroku/cli.rb:24:in `start'
C:/Program Files/Heroku/bin/heroku:29:in `<main>'

Thanks...

**Comment by ransombriggs** [comment]
Could you please try running the command again (it may have been a bad download) and if it does not work, attach the command you are attempting to run as well as the output of `heroku version`

**Comment by mhutter** [comment]
I observe the same problem on a fresh install of the heroku toolbelt on CentOS 7

```
$ heroku version
heroku-cli: Installing Toolbelt v4... !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       SHA mismatch for heroku-cli (RuntimeError)
    Command:     heroku version
    HTTP Proxy:  http://corporate.proxy:8080
    HTTPS Proxy: http://corporate.proxy:8080
    Version:     heroku-toolbelt/3.42.37 (x86_64-linux) ruby/2.3.0
    Error ID:    aeb6919219ad4294b056e0b9666b9d18


    More information in /home/user/.heroku/error.log
```

and the `.heroku/error.log`:

```
Heroku client internal error.
SHA mismatch for heroku-cli
/usr/local/heroku/lib/heroku/jsplugin.rb:146:in `setup'
/usr/local/heroku/lib/heroku/cli.rb:27:in `start'
/usr/local/heroku/bin/heroku:24:in `<main>'
```

I have tried multiple times with different commands, to no avail.

Is there a way to get the download URL so I can try downloading the file directly?

**Comment by ransombriggs** [comment]
@mhutter The download URLs are available here: https://cli-assets.heroku.com/master/manifest.json .  For your platform, you would want to download https://cli-assets.heroku.com/master/4.27.23-df3c8ac/linux/amd64/heroku-cli and verify it matches the SHA 49f642ecd566dca9222d742bba2e785552c5e4e2 .  Assuming a proper download, you would want to drop it in `~/.heroku/heroku-cli`.  In the future you may get errors when you try and update again, please let me know if you do and I can help you debug this.

**Comment by mhutter** [comment]
@ransombriggs thanks for the info. Using the manifest I was able to download the binary and verify it, no problems at all.

I suspect our corporate proxy, which does SSL-scanning by performing a "man in the middle"-attack, to cause the problems. I'll probably be able to verify this next week (I requested `*.heroku.com` to be whitelisted from the scanning).

I have noticed that heroku maintains its own CA certificates in `~/.heroku/`. I tried to add our Proxy CA to that bundle, to no avail. It would be great if the Heroku client would instead use the OS'es CA certificates.

**Comment by ransombriggs** [comment]
@mhutter Do you happen to know what software your corporate proxy uses?  I have an extra computer with ubuntu that I was going to use as a proxy server so I can recreate proxy issues people have encountered, but want to make sure I match what people are experiencing.

**Comment by mhutter** [comment]
@ransombriggs that would be McAffee Web Gateway :-S

**Comment by mhutter** [comment]
Whitelisting `*.heroku.com` did resolve the issue for me.

**Comment by ransombriggs** [comment]
@mhutter Thanks for letting us know.  We have started work on integrating the OS certificates better so that other people do no encounter the same issue.
