### ISSUE TITLE
Heroku client internal error

### ISSUE THREAD

**Issue by huangziwen** [heroku/heroku#1820]
when i typed  heroku login i got this
 
Installing Heroku Toolbelt v4... !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       read timeout reached (Excon::Errors::Timeout)
    Command:     heroku login
    Version:     heroku/toolbelt/3.42.20 (i386-mingw32) ruby/1.9.3
    Error ID:    77b67d6d41d74e2eafe67bc69856ed25

    More information in C:/Users/lenovo/.heroku/error.log

and I tried to use heroku update,but it didn't work

**Comment by ransombriggs** [comment]
Could you try running heroku update again and pasting the output of that command, and the relevant output from .heroku/error.log as well?

**Comment by huangziwen** [comment]
this time i run the heroku update  i got this 

Installing Heroku Toolbelt v4... !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       An existing connection was forcibly closed by the remote host. - SSL_connect (Errno::ECONNRESET) (Excon
::Errors::SocketError)
    Command:     heroku update
    Version:     heroku/toolbelt/3.42.20 (i386-mingw32) ruby/1.9.3
    Error ID:    2d95a075ddf44e22994bb6cab3bbdf3f

 More information in C:/Users/lenovo/.heroku/error.log

and the .heroku/error.log 

Heroku client internal error.
An existing connection was forcibly closed by the remote host. - SSL_connect (Errno::ECONNRESET)
C:/Program Files/Heroku/vendor/gems/excon-0.45.4/lib/excon/ssl_socket.rb:120:in `connect_nonblock'
C:/Program Files/Heroku/vendor/gems/excon-0.45.4/lib/excon/ssl_socket.rb:120:in `initialize'
C:/Program Files/Heroku/vendor/gems/excon-0.45.4/lib/excon/connection.rb:387:in `new'
C:/Program Files/Heroku/vendor/gems/excon-0.45.4/lib/excon/connection.rb:387:in `socket'
C:/Program Files/Heroku/vendor/gems/excon-0.45.4/lib/excon/connection.rb:106:in `request_call'
C:/Program Files/Heroku/vendor/gems/excon-0.45.4/lib/excon/middlewares/mock.rb:47:in `request_call'
C:/Program Files/Heroku/vendor/gems/excon-0.45.4/lib/excon/middlewares/instrumentor.rb:22:in `request_call'
C:/Program Files/Heroku/vendor/gems/excon-0.45.4/lib/excon/middlewares/base.rb:15:in `request_call'
C:/Program Files/Heroku/vendor/gems/excon-0.45.4/lib/excon/middlewares/base.rb:15:in `request_call'
C:/Program Files/Heroku/vendor/gems/excon-0.45.4/lib/excon/middlewares/base.rb:15:in `request_call'
C:/Program Files/Heroku/vendor/gems/excon-0.45.4/lib/excon/connection.rb:233:in `request'
C:/Program Files/Heroku/vendor/gems/excon-0.45.4/lib/excon.rb:229:in `get'
C:/Program Files/Heroku/lib/heroku/jsplugin.rb:191:in `manifest'
C:/Program Files/Heroku/lib/heroku/jsplugin.rb:204:in `url'
C:/Program Files/Heroku/lib/heroku/jsplugin.rb:133:in `setup'
C:/Program Files/Heroku/lib/heroku/cli.rb:24:in `start'
C:/Program Files/Heroku/bin/heroku:29:in `<main>'


thank you for helping

**Comment by ransombriggs** [comment]
Sorry, but could you please try one more time, the second error is related to the first.  There is a download that the client is trying to pull that had issues yesterday, and that we are still investigating, but it appears to be working better now.  Please let us know if it does not work now.

**Comment by lufeihaidao** [comment]
Same issue! 

```
> heroku logs
heroku-cli: Installing Toolbelt v4...
```

why every command need install v4? I just want to make it work!
