### ISSUE TITLE
adding SSL certificate 500 internal server error

### ISSUE THREAD

**Issue by acmisiti** [heroku/heroku#1846]
I am trying to add ssl certificate to heroku and here is the command i run:

`heroku certs:add server.crt server.key`

Here is the error when I tail the heroku log file:

```
Heroku client internal error.
Expected(200) <=> Actual(500 InternalServerError)

/usr/local/heroku/vendor/gems/excon-0.45.4/lib/excon/middlewares/expects.rb:10:in `response_call'
/usr/local/heroku/vendor/gems/excon-0.45.4/lib/excon/middlewares/response_parser.rb:8:in `response_call'
/usr/local/heroku/vendor/gems/excon-0.45.4/lib/excon/connection.rb:372:in `response'
/usr/local/heroku/vendor/gems/excon-0.45.4/lib/excon/connection.rb:236:in `request'
/usr/local/heroku/vendor/gems/excon-0.45.4/lib/excon/connection.rb:297:in `post'
/usr/local/heroku/lib/heroku/command/certs.rb:241:in `block in post_to_ssl_doctor'
/usr/local/heroku/lib/heroku/helpers.rb:280:in `action'
/usr/local/heroku/lib/heroku/command/certs.rb:232:in `post_to_ssl_doctor'
/usr/local/heroku/lib/heroku/command/certs.rb:249:in `read_crt_and_key_through_ssl_doctor'
/usr/local/heroku/lib/heroku/command/certs.rb:265:in `read_crt_and_key'
/usr/local/heroku/lib/heroku/command/certs.rb:75:in `add'
/usr/local/heroku/lib/heroku/command.rb:212:in `run'
/usr/local/heroku/lib/heroku/cli.rb:30:in `start'
/usr/local/heroku/bin/heroku:24:in `<main>'
```

Already checked this out and commented but it is outdated https://github.com/heroku/heroku/issues/1087. Thanks

**Comment by dickeyxxx** [comment]
can you submit a support ticket? 500 errors mean it's not an issue with the CLI but something on the server.
