### ISSUE TITLE
Adding SSL Cert - InternalServerError

### ISSUE THREAD

**Issue by chriddyp** [heroku/heroku#1851]
Hi folks -- 
I'm trying to add SSL to my site from a cert that I've made with `lets encrypt`. 

```
$ heroku addons:create ssl:endpoint
```

```
$ heroku certs:add /etc/letsencrypt/live/dashboards.ly/fullchain.pem /etc/letsencrypt/live/dashboards.ly/privkey.pem
Resolving trust chain... failed
 !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       Expected(200) <=> Actual(500 InternalServerError)
 (Excon::Errors::InternalServerError)
    Command:     heroku certs:add /etc/letsencrypt/live/dashboards.ly/fullchain.pem /etc/letsencrypt/live/dashboards.ly/privkey.pem
    Version:     heroku-toolbelt/3.42.25 (x86_64-darwin10.8.0) ruby/1.9.3
    Error ID:    cfce57f8ba25433b94c6c9471bc5852c


    More information in /Users/chriddyp/.heroku/error.log
```
```
$ cat ~/.heroku/error.log
Heroku client internal error.
Expected(200) <=> Actual(500 InternalServerError)

/Users/chriddyp/.heroku/client/vendor/gems/excon-0.45.4/lib/excon/middlewares/expects.rb:10:in `response_call'
/Users/chriddyp/.heroku/client/vendor/gems/excon-0.45.4/lib/excon/middlewares/response_parser.rb:8:in `response_call'
/Users/chriddyp/.heroku/client/vendor/gems/excon-0.45.4/lib/excon/connection.rb:372:in `response'
/Users/chriddyp/.heroku/client/vendor/gems/excon-0.45.4/lib/excon/connection.rb:236:in `request'
/Users/chriddyp/.heroku/client/vendor/gems/excon-0.45.4/lib/excon/connection.rb:297:in `post'
/Users/chriddyp/.heroku/client/lib/heroku/command/certs.rb:241:in `block in post_to_ssl_doctor'
/Users/chriddyp/.heroku/client/lib/heroku/helpers.rb:280:in `action'
/Users/chriddyp/.heroku/client/lib/heroku/command/certs.rb:232:in `post_to_ssl_doctor'
/Users/chriddyp/.heroku/client/lib/heroku/command/certs.rb:249:in `read_crt_and_key_through_ssl_doctor'
/Users/chriddyp/.heroku/client/lib/heroku/command/certs.rb:265:in `read_crt_and_key'
/Users/chriddyp/.heroku/client/lib/heroku/command/certs.rb:75:in `add'
/Users/chriddyp/.heroku/client/lib/heroku/command.rb:212:in `run'
/Users/chriddyp/.heroku/client/lib/heroku/cli.rb:30:in `start'
/usr/local/heroku/bin/heroku:24:in `<main>'
```

Any ideas? Thanks!

**Comment by chriddyp** [comment]
Fixed with `$ heroku update`. Thanks!
