### ISSUE TITLE
Updating an SSL certificate fails with InternalServerError

### ISSUE THREAD

**Issue by porridge** [heroku/heroku#1855]
Here's a failure:

```
$ heroku certs:update --app zyncrender WILDCARD.zyncrender.com.chained.pem WILDCARD.zyncrender.com.key 
Resolving trust chain... failed
 !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       Expected(200) <=> Actual(500 InternalServerError)
 (Excon::Errors::InternalServerError)
    Command:     heroku certs:update --app zyncrender WILDCARD.zyncrender.com.chained.pem WILDCARD.zyncrender.com.key
    Version:     heroku-toolbelt/3.42.25 (x86_64-linux) ruby/1.9.3
    Error ID:    9e9a5509e47147ab86b46f04edad7f4e


    More information in /usr/local/google/home/porridge/.heroku/error.log
```

The log file has:

```
2015/12/15 19:39:45 running heroku-cli/4.27.9-cce0260 (amd64-linux) go1.5.2 from /usr/local/google/home/porridge/.heroku/heroku-cli
Heroku client internal error.
Expected(200) <=> Actual(500 InternalServerError)

/usr/local/heroku/vendor/gems/excon-0.45.4/lib/excon/middlewares/expects.rb:10:in `response_call'
/usr/local/heroku/vendor/gems/excon-0.45.4/lib/excon/middlewares/response_parser.rb:8:in `response_call'
/usr/local/heroku/vendor/gems/excon-0.45.4/lib/excon/connection.rb:372:in `response'
/usr/local/heroku/vendor/gems/excon-0.45.4/lib/excon/connection.rb:236:in `request'
/usr/local/heroku/vendor/gems/excon-0.45.4/lib/excon/connection.rb:297:in `post'
/usr/local/heroku/lib/heroku/command/certs.rb:241:in `block in post_to_ssl_doctor'
/usr/local/heroku/lib/heroku/helpers.rb:280:in `action'
/usr/local/heroku/lib/heroku/command/certs.rb:232:in `post_to_ssl_doctor'
/usr/local/heroku/lib/heroku/command/certs.rb:249:in `read_crt_and_key_through_ssl_doctor'
/usr/local/heroku/lib/heroku/command/certs.rb:265:in `read_crt_and_key'
/usr/local/heroku/lib/heroku/command/certs.rb:93:in `update'
/usr/local/heroku/lib/heroku/command.rb:212:in `run'
/usr/local/heroku/lib/heroku/cli.rb:30:in `start'
/usr/local/heroku/bin/heroku:24:in `<main>'
```

I just installed the toolbelt using ```wget -O- https://toolbelt.heroku.com/install.sh | sh``` an hour ago or so, and the plugins seem to be up to date:

```
porridge@kielonek:~/zync/admin-scripts/ansible/roles/public/files$ heroku update
Updating plugins... no plugins to update.
porridge@kielonek:~/zync/admin-scripts/ansible/roles/public/files$ 
```

**Comment by dickeyxxx** [comment]
can you file a support ticket? this is not an issue with the CLI
