### ISSUE TITLE
Error downgrading Postgresql

### ISSUE THREAD

**Issue by dfalkner** [heroku/heroku#1861]
When I run this command to downgrade a pg database in my app fcg-reporting-service-staging:

heroku pg:copy postgres://u7v4t7f1b2v430:p6s2rlld4aa0ih37ahqhrr91das@ec2-107-22-163-193.compute-1.amazonaws.com:5432/d8r0q77e176rpo postgres://u4qcs8md94sujm:pbmjmbtg4d5f5p3tbou7ovtbfg8@ec2-54-83-35-134.compute-1.amazonaws.com:5502/d6mu5hteqrgdmv  --app fcg-reporting-service-staging --confirm d6mu5hteqrgdmv

**I get the following message:**
 !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       undefined method `resource_name' for nil:NilClass (NoMethodError)
    Command:     heroku pg:copy postgres://u7v4t7f1b2v430:p6s2rlld4aa0ih37ahqhrr91das@ec2-107-22-163-193.compute-1.amazonaws.com:5432/d8r0q77e176rpo postgres://u4qcs8md94sujm:pbmjmbtg4d5f5p3tbou7ovtbfg8@ec2-54-83-35-134.compute-1.amazonaws.com:5502/d6mu5hteqrgdmv --app fcg-reporting-service-staging --confirm d6mu5hteqrgdmv
    Version:     heroku-toolbelt/3.42.25 (x86_64-darwin10.8.0) ruby/1.9.3
    Error ID:    f107363a64d64152b3a8ef31d7501ebd

    More information in /Users/danefalkner/.heroku/error.log

**And the following error log:**
2015/12/18 09:45:46 running heroku-cli/4.27.9-cce0260 (amd64-darwin) go1.5.2 from /Users/danefalkner/.heroku/heroku-cli
Heroku client internal error.
undefined method `resource_name' for nil:NilClass
/Users/danefalkner/.heroku/client/lib/heroku/client/heroku_postgresql.rb:39:in `resource_name'
/Users/danefalkner/.heroku/client/lib/heroku/client/heroku_postgresql.rb:139:in `pg_copy'
/Users/danefalkner/.heroku/client/lib/heroku/command/pg_backups.rb:48:in `copy'
/Users/danefalkner/.heroku/client/lib/heroku/command.rb:212:in `run'
/Users/danefalkner/.heroku/client/lib/heroku/cli.rb:30:in `start'
/usr/local/bin/heroku:24:in `<main>'

**Comment by dickeyxxx** [comment]
This is usually because the ruby installation isn't properly compiled. Try reinstalling ruby and/or the toolbelt.

Also you probably shouldn't post your database credentials on the internet like that. I removed them for you.
