### ISSUE TITLE
Heroku client internal error while running several commands

### ISSUE THREAD

**Issue by danielocallaghan** [heroku/heroku#1870]
I just installed the heroku cli today via the osx installer, I've successfully logged in but running the command `heroku apps` returns an internal error:

```
$ heroku auth:login
Enter your Heroku credentials.
Email: doc@trineo.com
Password (typing will be hidden):
 ▸    Authentication failure.
daniel@Daniels-MacBook-Pro:~/Sites/cco/api.cco.io
[master]$ heroku auth:login
Enter your Heroku credentials.
Email: doc@trineo.com
Password (typing will be hidden)
$ heroku apps
 !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       undefined method `netrc_filename' for Netrc:Class (NoMethodError)
    Command:     heroku apps
    Version:     heroku-toolbelt/3.42.25 (x86_64-darwin10.8.0) ruby/1.9.3
    Error ID:    c1a2b26f24da4ab7a4c80ea682cf1c58


    More information in /Users/daniel/.heroku/error.log

$ cat /Users/daniel/.heroku/error.log
2016/01/06 17:19:06 running heroku-cli/4.27.9-cce0260 (amd64-darwin) go1.5.2 from /Users/daniel/.heroku/heroku-cli
Heroku client internal error.
undefined method `netrc_filename' for Netrc:Class
/usr/local/heroku/lib/heroku/auth.rb:138:in `netrc_path'
/usr/local/heroku/lib/heroku/auth.rb:160:in `rescue in netrc'
/usr/local/heroku/lib/heroku/auth.rb:151:in `netrc'
/usr/local/heroku/lib/heroku/auth.rb:178:in `read_credentials'
/usr/local/heroku/lib/heroku/auth.rb:113:in `get_credentials'
/usr/local/heroku/lib/heroku/auth.rb:89:in `password'
/usr/local/heroku/lib/heroku/auth.rb:17:in `api'
/usr/local/heroku/lib/heroku/command/base.rb:72:in `api'
/usr/local/heroku/lib/heroku/command/apps.rb:35:in `index'
/usr/local/heroku/lib/heroku/command.rb:212:in `run'
/usr/local/heroku/lib/heroku/cli.rb:30:in `start'
/usr/local/bin/heroku:24:in `<main>'
```

**Comment by ransombriggs** [comment]
@danielocallaghan Could you please remove the `~/.heroku` directory and try again?

**Comment by danielocallaghan** [comment]
@ransombriggs looks like the error persists after trying that:

```
daniel@Daniels-MacBook-Pro:~
$ rm -rf .heroku
daniel@Daniels-MacBook-Pro:~
$ heroku auth:login
heroku-cli: Installing Toolbelt v4... done
For more information on Toolbelt v4: https://github.com/heroku/heroku-cli
heroku-cli: Adding dependencies... done
heroku-cli: Installing core plugins... done
Enter your Heroku credentials.
Email: doc@trineo.com
Password (typing will be hidden):
Logged in as doc@trineo.com
daniel@Daniels-MacBook-Pro:~
$ heroku apps
 !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       undefined method `netrc_filename' for Netrc:Class (NoMethodError)
    Command:     heroku apps
    Version:     heroku-toolbelt/3.42.25 (x86_64-darwin10.8.0) ruby/1.9.3
    Error ID:    46f43e8d1fac41f98e872f1565fe1f40


    More information in /Users/daniel/.heroku/error.log

daniel@Daniels-MacBook-Pro:~
$ cat .heroku/error.log
2016/01/07 10:02:52 running heroku-cli/4.27.9-cce0260 (amd64-darwin) go1.5.2 from /Users/daniel/.heroku/heroku-cli
2016/01/07 10:02:52 heroku-cli: Adding dependencies...
2016/01/07 10:02:59  done
2016/01/07 10:02:59 heroku-cli: Installing core plugins...
2016/01/07 10:03:10  done
2016/01/07 10:03:10 running heroku-cli/4.27.9-cce0260 (amd64-darwin) go1.5.2 from /Users/daniel/.heroku/heroku-cli
2016/01/07 10:03:10 running heroku-cli/4.27.9-cce0260 (amd64-darwin) go1.5.2 from /Users/daniel/.heroku/heroku-cli
2016/01/07 10:03:10 Email:
2016/01/07 10:03:54 running heroku-cli/4.27.9-cce0260 (amd64-darwin) go1.5.2 from /Users/daniel/.heroku/heroku-cli
Heroku client internal error.
undefined method `netrc_filename' for Netrc:Class
/usr/local/heroku/lib/heroku/auth.rb:138:in `netrc_path'
/usr/local/heroku/lib/heroku/auth.rb:160:in `rescue in netrc'
/usr/local/heroku/lib/heroku/auth.rb:151:in `netrc'
/usr/local/heroku/lib/heroku/auth.rb:178:in `read_credentials'
/usr/local/heroku/lib/heroku/auth.rb:113:in `get_credentials'
/usr/local/heroku/lib/heroku/auth.rb:89:in `password'
/usr/local/heroku/lib/heroku/auth.rb:17:in `api'
/usr/local/heroku/lib/heroku/command/base.rb:72:in `api'
/usr/local/heroku/lib/heroku/command/apps.rb:35:in `index'
/usr/local/heroku/lib/heroku/command.rb:212:in `run'
/usr/local/heroku/lib/heroku/cli.rb:30:in `start'
/usr/local/bin/heroku:24:in `<main>'
```

**Comment by danielocallaghan** [comment]
got this working now by following the suggestion from @keithpitty at: https://github.com/heroku/heroku/issues/1865
