### ISSUE TITLE
 SSL_connect returned=1 errno=0 state=unknown state: unknown protocol (OpenSSL::SSL::SSLError) (Excon::Errors::SocketError)

### ISSUE THREAD

**Issue by 108anup** [heroku/heroku#1885]
heroku-cli: Installing Toolbelt v4...SSL_connect returned=1 errno=0 state=unknown state: unknown protocol (OpenSSL::SSL::SSLError)
/usr/local/heroku/vendor/gems/excon-0.45.4/lib/excon/ssl_socket.rb:120:in `connect_nonblock'
/usr/local/heroku/vendor/gems/excon-0.45.4/lib/excon/ssl_socket.rb:120:in `initialize'
/usr/local/heroku/vendor/gems/excon-0.45.4/lib/excon/connection.rb:387:in `new'
/usr/local/heroku/vendor/gems/excon-0.45.4/lib/excon/connection.rb:387:in `socket'
/usr/local/heroku/vendor/gems/excon-0.45.4/lib/excon/connection.rb:106:in `request_call'
/usr/local/heroku/vendor/gems/excon-0.45.4/lib/excon/middlewares/mock.rb:47:in `request_call'
/usr/local/heroku/vendor/gems/excon-0.45.4/lib/excon/middlewares/instrumentor.rb:22:in `request_call'
/usr/local/heroku/vendor/gems/excon-0.45.4/lib/excon/middlewares/base.rb:15:in `request_call'
/usr/local/heroku/vendor/gems/excon-0.45.4/lib/excon/middlewares/base.rb:15:in `request_call'
/usr/local/heroku/vendor/gems/excon-0.45.4/lib/excon/middlewares/base.rb:15:in `request_call'
/usr/local/heroku/vendor/gems/excon-0.45.4/lib/excon/connection.rb:233:in `request'
/usr/local/heroku/vendor/gems/excon-0.45.4/lib/excon.rb:229:in `get'
/usr/local/heroku/lib/heroku/jsplugin.rb:210:in `manifest'
/usr/local/heroku/lib/heroku/jsplugin.rb:223:in `url'
/usr/local/heroku/lib/heroku/jsplugin.rb:139:in `setup'
/usr/local/heroku/lib/heroku/cli.rb:27:in `start'
/usr/bin/heroku:25:in `<main>'
 !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       SSL_connect returned=1 errno=0 state=unknown state: unknown protocol (OpenSSL::SSL::SSLError) (Excon::Errors::SocketError)
    Command:     heroku login
    HTTP Proxy:  http://username:password@host:port/
    HTTPS Proxy: https://username:password@host:port/
    Version:     heroku-toolbelt/3.42.31 (x86_64-linux) ruby/1.9.3

**Comment by ransombriggs** [comment]
@108anup Could you please try an alternate way (curl / web browser) of downloading the following url?  https://cli-assets.heroku.com/master/4.27.15-535a059/darwin/amd64/heroku-cli  This will help me determine whether the problem is in your network configuration or the heroku client.  One thing I am finding mildly confusing (assuming I am reading the stack trace correctly) is that it appears that it was able to succesfully download https://cli-assets.heroku.com/master/manifest.json without any issues.

**Comment by 108anup** [comment]
I had to use: 
$ npm config set strict-ssl=false
and use a network tunnel as a work around to the issue.
