### ISSUE TITLE
Weird SSL Problem.

### ISSUE THREAD

**Issue by MrWilhelm** [heroku/heroku#1892]
Here are details
http://stackoverflow.com/questions/35255037/i-cant-run-rake-dbmigrate-on-heroku/35255942#35255942

When I try to run heroku logs, I get this error. It is very unstable. With proxy I can "sometimes" make commands work. Also I can not connect to heroku.com It says unsecured connection. 

Firefox, Ubuntu 14.04 

!    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       hostname "api.heroku.com" does not match the server certificate (OpenSSL::SSL::SSLError)
    Command:     heroku logs
    Version:     heroku-toolbelt/3.42.33 (x86_64-linux) ruby/2.2.2
    Error ID:    e7d2409f80f746cbb8308e2539a544bd

    More information in /home/xelamony/.heroku/error.log

Those are some of the errors I get when I try to "heroku run rake db:migrate", "heroku run rails c"

```
▸    Hostname/IP doesn't match certificate's altnames: "Host: api.heroku.com. is not in the cert's altnames: DNS:*.demdex.net, DNS:demdex.net"

 ▸    Hostname/IP doesn't match certificate's altnames: "Host: api.heroku.com. is not in the cert's altnames: DNS:*.securefirmportal.com, DNS:securefirmportal.com"
```

**Comment by ransombriggs** [comment]
@MrWilhelm your proxy software appears to be using its own certificate rather than propagating the heroku certificate, therefore the heroku toolbelt rejects your proxy's certificate because the hostname does not match.  This suggests that your proxy is not configured correctly, rather than a problem in the heroku toolbelt.

**Comment by gkop** [comment]
Just wanted to chime in that I received this error today, just once. Haven't been able to replicate. On Comcast residential internet in San Francisco, no proxy. Unfortunately I closed the terminal buffer so I can't paste the altnames given.

**Comment by hollsk** [comment]
I'm also getting very similar SSL errors today:

```
 !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       hostname "manager-api.heroku.com" does not match the server certificate (OpenSSL::SSL::SSLError) (Excon::Errors::SocketError)
    Backtrace:   /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/openssl/ssl.rb:139:in `post_connection_check'
                 /Library/Ruby/Gems/2.0.0/gems/excon-0.31.0/lib/excon/ssl_socket.rb:86:in `initialize'
                 /Library/Ruby/Gems/2.0.0/gems/excon-0.31.0/lib/excon/connection.rb:410:in `new'
                 /Library/Ruby/Gems/2.0.0/gems/excon-0.31.0/lib/excon/connection.rb:410:in `socket'
                 /Library/Ruby/Gems/2.0.0/gems/excon-0.31.0/lib/excon/connection.rb:122:in `request_call'
                 /Library/Ruby/Gems/2.0.0/gems/excon-0.31.0/lib/excon/middlewares/mock.rb:42:in `request_call'
                 /Library/Ruby/Gems/2.0.0/gems/excon-0.31.0/lib/excon/middlewares/instrumentor.rb:22:in `request_call'
                 /Library/Ruby/Gems/2.0.0/gems/excon-0.31.0/lib/excon/middlewares/base.rb:15:in `request_call'
                 /Library/Ruby/Gems/2.0.0/gems/excon-0.31.0/lib/excon/middlewares/base.rb:15:in `request_call'
                 /Library/Ruby/Gems/2.0.0/gems/excon-0.31.0/lib/excon/middlewares/base.rb:15:in `request_call'
                 /Library/Ruby/Gems/2.0.0/gems/excon-0.31.0/lib/excon/connection.rb:265:in `request'
                 /Library/Ruby/Gems/2.0.0/gems/heroku-3.3.0/lib/heroku/client/organizations.rb:31:in `request'
                 /Library/Ruby/Gems/2.0.0/gems/heroku-3.3.0/lib/heroku/client/organizations.rb:76:in `get_orgs'
                 /Library/Ruby/Gems/2.0.0/gems/heroku-3.3.0/lib/heroku/command/base.rb:53:in `org'
                 /Library/Ruby/Gems/2.0.0/gems/heroku-3.3.0/lib/heroku/command/apps.rb:237:in `create'
                 /Library/Ruby/Gems/2.0.0/gems/heroku-3.3.0/lib/heroku/command.rb:218:in `run'
                 /Library/Ruby/Gems/2.0.0/gems/heroku-3.3.0/lib/heroku/cli.rb:28:in `start'
                 /Library/Ruby/Gems/2.0.0/gems/heroku-3.3.0/bin/heroku:17:in `<top (required)>'
                 /usr/bin/heroku:23:in `load'
                 /usr/bin/heroku:23:in `<main>'

    Command:     heroku create
    Version:     heroku-gem/3.3.0 (universal.x86_64-darwin13) ruby/2.0.0
```

I'm not running a proxy either. Based in the UK, using EE broadband (unlike OP, no problems accessing heroku.com though).

**Comment by dickeyxxx** [comment]
you are running an ancient version
