### ISSUE TITLE
CLI issue similar to #1057, but on OS X with rvm

### ISSUE THREAD

**Issue by gpolyn** [heroku/heroku#1917]
Issue similar to [#1057](https://github.com/heroku/heroku/issues/1057), but on OS X (10.10.5) with rvm.

```
/Users/me/.heroku/client/lib/heroku/auth.rb:7:in `require': cannot load such file -- netrc (LoadError)
	from /Users/me/.heroku/client/lib/heroku/auth.rb:7:in `<top (required)>'
	from /Users/me/.heroku/client/lib/heroku/client.rb:3:in `require'
	from /Users/me/.heroku/client/lib/heroku/client.rb:3:in `<top (required)>'
	from /Users/me/.rvm/gems/ruby-2.1.2@global/gems/heroku-2.11.1/lib/heroku.rb:6:in `require'
	from /Users/me/.rvm/gems/ruby-2.1.2@global/gems/heroku-2.11.1/lib/heroku.rb:6:in `<top (required)>'
	from /Users/me/.rvm/gems/ruby-2.1.2@global/gems/heroku-2.11.1/bin/heroku:6:in `require'
	from /Users/me/.rvm/gems/ruby-2.1.2@global/gems/heroku-2.11.1/bin/heroku:6:in `<top (required)>'
	from /Users/me/.rvm/rubies/ruby-2.1.2/bin/heroku:23:in `load'
	from /Users/me/.rvm/rubies/ruby-2.1.2/bin/heroku:23:in `<main>'
	from /Users/me/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
	from /Users/me/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'
```
Attempted remedy in ruby-2.1.2 was to add netrc to global gemset:

```
$ ls /Users/me/.rvm/gems/ruby-2.1.2@global/gems
bundler-1.6.2		foreman-0.25.0		launchy-0.4.0		rack-1.3.5		rdoc-4.1.0		rvm-1.11.3.9
bundler-unload-1.0.2	gem-wrappers-1.2.4	mime-types-1.16		rack-test-0.6.1		rest-client-1.6.7	term-ansicolor-1.0.7
configuration-1.2.0	gem-wrappers-1.2.7	minitest-2.7.0		rake-0.8.7		rubygems-bundler-1.4.4	test-unit-2.1.2.0
executable-hooks-1.3.2	heroku-2.11.1		netrc-0.11.0		rake-10.1.0		rubyzip-0.9.4		thor-0.14.6
```

I acknowledge this may be more an rvm than heroku issue.

**Comment by gpolyn** [comment]
...sorry, think this is too arcane to pursue and likely the result of the involvement of the "heroku" gem in my Gemfile.
