### ISSUE TITLE
Getting error while invoking heroku login

### ISSUE THREAD

**Issue by agarwal-mayank** [heroku/heroku#1930]
Hi,

I installed heroku yesterday and it was working fine. But when I tried to rerun it today, it started giving me error. I unistalled and reinstalled several times but to no avail.

This is the error I am getting:
```
heroku-cli: Installing Toolbelt v4... !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       An existing connection was forcibly closed by the remote host.
(Errno::ECONNRESET) (Excon::Errors::SocketError)
    Command:     heroku
    Version:     heroku/toolbelt/3.42.45 (i386-mingw32) ruby/2.1.7
    Error ID:    a79689b84ad549c498f98645857d78db


    More information in C:/Users/Maitri/.heroku/error.log

Here is the error log:
Heroku client internal error.
An existing connection was forcibly closed by the remote host. (Errno::ECONNRESET)
C:/Program Files (x86)/Heroku/ruby-2.1.7/lib/ruby/2.1.0/openssl/buffering.rb:182:in `sysread_nonblock'
C:/Program Files (x86)/Heroku/ruby-2.1.7/lib/ruby/2.1.0/openssl/buffering.rb:182:in `read_nonblock'
C:/Program Files (x86)/Heroku/vendor/gems/excon-0.47.0/lib/excon/socket.rb:168:in `read_nonblock'
C:/Program Files (x86)/Heroku/vendor/gems/excon-0.47.0/lib/excon/socket.rb:35:in `read'
C:/Program Files (x86)/Heroku/vendor/gems/excon-0.47.0/lib/excon/response.rb:154:in `parse'
C:/Program Files (x86)/Heroku/vendor/gems/excon-0.47.0/lib/excon/middlewares/response_parser.rb:6:in `response_call'
C:/Program Files (x86)/Heroku/vendor/gems/excon-0.47.0/lib/excon/connection.rb:372:in `response'
C:/Program Files (x86)/Heroku/vendor/gems/excon-0.47.0/lib/excon/connection.rb:236:in `request'
C:/Program Files (x86)/Heroku/vendor/gems/excon-0.47.0/lib/excon.rb:230:in `get'
C:/Program Files (x86)/Heroku/lib/heroku/jsplugin.rb:139:in `setup'
C:/Program Files (x86)/Heroku/lib/heroku/cli.rb:27:in `start'
C:/Program Files (x86)/Heroku/bin/heroku:29:in `<main>'
```

**Comment by ransombriggs** [comment]
@agarwal-mayank Sorry for the delayed response, but are you still getting this error?  This may have been due to a temporary network issue.

**Comment by agarwal-mayank** [comment]
Hi,

The error got resolved. It was my stupid antivirus. It kept on blocking the heroku-cli file. 
I saw it in one of the posts, someone else was having the same issue.

Got resolved now.

Thanks,
Mayank
