### ISSUE TITLE
Heroku client internal error.

### ISSUE THREAD

**Issue by Hareesh007** [heroku/heroku#1932]
I am new To Heroku ,first time i try to install Heroku toolbelt and after that run the command heroku login i am getting this error 
 heroku -version
 !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       undefined method `[]' for nil:NilClass (NoMethodError)
    Command:     heroku -version
    Version:     heroku-toolbelt/3.42.50 (i686-linux) ruby/2.0.0
    Error ID:    77319efb12804249b20ed45248dd6194

    More information in /home/giri/.heroku/error.log
and **error log file
**
Heroku client internal error.
undefined method `[]' for nil:NilClass
/usr/local/heroku/lib/heroku/jsplugin.rb:60:in `commands'
/usr/local/heroku/lib/heroku/jsplugin.rb:228:in `find_command'
/usr/local/heroku/lib/heroku/jsplugin.rb:13:in `try_takeover'
/usr/local/heroku/lib/heroku/cli.rb:28:in `start'
/usr/local/heroku/bin/heroku:25:in `<main>'

**Comment by dickeyxxx** [comment]
are you still getting this error?

**Comment by odarino** [comment]
bump this thread. I've faced this error. It still stands in " heroku-cli: Installing CLI ". How can I fix this. Thank you
