### ISSUE TITLE
panic message when auto update toolbelt

### ISSUE THREAD

**Issue by Nivg** [heroku/heroku#1949]
Hello,

From yesterday when trying to use any toolbelt command on windows, I am getting the following message:

1. Happens only once:

> heroku-cli: Updating CLI...panic: Get https://cli-assets.heroku.com/branches/stable/manifest.json: dial tcp: lookup cli-assets.heroku.com: getaddrinfow: No such
 host is known.

goroutine 1 [running]:
panic(0x6e0920, 0x10f7ba80)
        /usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:481 +0x326
main.must(0x234508, 0x10f7ba80)
        /Users/jdickey/src/github.com/heroku/cli/main.go:247 +0x44
main.getUpdateManifest(0x722b30, 0x6, 0x1b)
        /Users/jdickey/src/github.com/heroku/cli/main.go:259 +0x144
main.update()
        /Users/jdickey/src/github.com/heroku/cli/main.go:145 +0x234
main.main()
        /Users/jdickey/src/github.com/heroku/cli/main.go:46 +0x2b
heroku-cli: Updating CLI...panic: Get https://cli-assets.heroku.com/branches/stable/manifest.json: dial tcp: lookup cli-assets.heroku.com: getaddrinfow: No such
 host is known.

goroutine 1 [running]:
panic(0x6e0920, 0x10cafa80)
        /usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:481 +0x326
main.must(0x354508, 0x10cafa80)
        /Users/jdickey/src/github.com/heroku/cli/main.go:247 +0x44
main.getUpdateManifest(0x722b30, 0x6, 0x1b)
        /Users/jdickey/src/github.com/heroku/cli/main.go:259 +0x144
main.update()
        /Users/jdickey/src/github.com/heroku/cli/main.go:145 +0x234
main.main()
        /Users/jdickey/src/github.com/heroku/cli/main.go:46 +0x2b
heroku-cli: Updating CLI...panic: Get https://cli-assets.heroku.com/branches/stable/manifest.json: dial tcp: lookup cli-assets.heroku.com: getaddrinfow: No such
 host is known.

goroutine 1 [running]:
panic(0x6e0920, 0x10eafa80)
        /usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:481 +0x326
main.must(0x234508, 0x10eafa80)
        /Users/jdickey/src/github.com/heroku/cli/main.go:247 +0x44
main.getUpdateManifest(0x722b30, 0x6, 0x1b)
        /Users/jdickey/src/github.com/heroku/cli/main.go:259 +0x144
main.update()
        /Users/jdickey/src/github.com/heroku/cli/main.go:145 +0x234
main.main()
        /Users/jdickey/src/github.com/heroku/cli/main.go:46 +0x2b

2. Each time I try a command, for example heroku logs -t:

> heroku-cli: Updating to 5.1.5-b4610e8...panic:

Thanks for the help

**Comment by dickeyxxx** [comment]
The first one is just because it wasn't able to connect to the internet I think. The second one though, I'm not sure but I think a user had this in an older version. Try deleting `%LOCALAPPDATA%\heroku` (assuming this is on windows, you didn't say but it looks like it might be)

**Comment by Nivg** [comment]
Yes it's on window 8.1

I have already deleted the local folder and still got the same error.
I will try to download the newest version manually and see if it's helps bypassing this issue.
