### ISSUE TITLE
ps:stop and ps:kill emit type error

### ISSUE THREAD

**Issue by stefan-kolb** [heroku/heroku#1951]
Running `heroku ps:stop scheduler.3397` emits:

```
C:\Users\Stefan\AppData\Local\heroku\tmp\heroku-script-476813411:14
cmd.run(ctx)
   ^

TypeError: Cannot read property 'run' of undefined
    at Object.<anonymous> (C:\Users\Stefan\AppData\Local\heroku\tmp\heroku-script-476813411:14:4)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:159:18)
    at node.js:444:3
```

This worked in previous versions of the CLI.

**Comment by stefan-kolb** [comment]
Looks like this is some incompatibility issue on my system. After reinstalling Git it seems to work again, strange...
