### ISSUE TITLE
Heroku login or heroku create is not working

### ISSUE THREAD

**Issue by vedsolution** [heroku/heroku#1960]
Error:       Connection reset by peer - SSL_connect (Errno::ECONNRESET) (Excon::Errors::SocketError)
    Command:     heroku --version
    Version:     heroku-toolbelt/3.43.2 (x86_64-darwin10.8.0) ruby/1.9.3
    Error ID:    c3db35e1c5474b73b5719740819c14fc

**Comment by vedsolution** [comment]
In error.log file 
Heroku client internal error.
Connection reset by peer - SSL_connect (Errno::ECONNRESET)
/Users/ved/.heroku/client/vendor/gems/excon-0.47.0/lib/excon/ssl_socket.rb:120:in `connect_nonblock'
/Users/ved/.heroku/client/vendor/gems/excon-0.47.0/lib/excon/ssl_socket.rb:120:in `initialize'
/Users/ved/.heroku/client/vendor/gems/excon-0.47.0/lib/excon/connection.rb:387:in `new'
/Users/ved/.heroku/client/vendor/gems/excon-0.47.0/lib/excon/connection.rb:387:in `socket'
/Users/ved/.heroku/client/vendor/gems/excon-0.47.0/lib/excon/connection.rb:106:in `request_call'
/Users/ved/.heroku/client/vendor/gems/excon-0.47.0/lib/excon/middlewares/mock.rb:47:in `request_call'
/Users/ved/.heroku/client/vendor/gems/excon-0.47.0/lib/excon/middlewares/instrumentor.rb:25:in `request_call'
/Users/ved/.heroku/client/vendor/gems/excon-0.47.0/lib/excon/middlewares/base.rb:15:in `request_call'
/Users/ved/.heroku/client/vendor/gems/excon-0.47.0/lib/excon/middlewares/base.rb:15:in `request_call'
/Users/ved/.heroku/client/vendor/gems/excon-0.47.0/lib/excon/middlewares/base.rb:15:in `request_call'
/Users/ved/.heroku/client/vendor/gems/excon-0.47.0/lib/excon/connection.rb:233:in `request'
/Users/ved/.heroku/client/vendor/gems/excon-0.47.0/lib/excon.rb:230:in `get'
/Users/ved/.heroku/client/lib/heroku/jsplugin.rb:246:in `manifest'
/Users/ved/.heroku/client/lib/heroku/jsplugin.rb:259:in `url'
/Users/ved/.heroku/client/lib/heroku/jsplugin.rb:149:in `block (2 levels) in setup'
/Users/ved/.heroku/client/lib/heroku/jsplugin.rb:137:in `open'
/Users/ved/.heroku/client/lib/heroku/jsplugin.rb:137:in `block in setup'
/usr/local/heroku/ruby/lib/ruby/1.9.1/tmpdir.rb:83:in `mktmpdir'
/Users/ved/.heroku/client/lib/heroku/jsplugin.rb:135:in `setup'
/Users/ved/.heroku/client/lib/heroku/cli.rb:27:in `start'
/usr/local/bin/heroku:24:in `<main>'

**Comment by ransombriggs** [comment]
@vedsolution are you behind a network proxy or firewall?
