### ISSUE TITLE
Heroku server certificate issue

### ISSUE THREAD

**Issue by rochebox** [heroku/heroku#1972]
Hi I'm having a problem in deploying a rails project to Heroku  I am in the Firehose Project. https://www.thefirehoseproject.com/   There is a stack-over flow request with basically the same issue, but there is no solution there...(or I didn't see it).

In a vagrant development environment (after creating a rails project and setting up a gitHub repository (all fine) when I try 'heroku create file-name', I get back a error (a server certificate issue??) as follows:

[Web Dev]:  /vagrant/src/nomster2 $ heroku create nomster2-rochebox
 !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       hostname "manager-api.heroku.com" does not match the server certificate (OpenSSL::SSL::SSLError) (Excon::Errors::SocketError)
    Backtrace:   /home/vagrant/.rbenv/versions/2.0.0-p353/lib/ruby/2.0.0/openssl/ssl.rb:139:in `post_connection_check'
                 /home/vagrant/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/excon-0.31.0/lib/excon/ssl_socket.rb:86:in `initialize'
                 /home/vagrant/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/excon-0.31.0/lib/excon/connection.rb:410:in `new'
                 /home/vagrant/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/excon-0.31.0/lib/excon/connection.rb:410:in `socket'
                 /home/vagrant/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/excon-0.31.0/lib/excon/connection.rb:122:in `request_call'
                 /home/vagrant/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/excon-0.31.0/lib/excon/middlewares/mock.rb:42:in `request_call'
                 /home/vagrant/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/excon-0.31.0/lib/excon/middlewares/instrumentor.rb:22:in `request_call'
                 /home/vagrant/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/excon-0.31.0/lib/excon/middlewares/base.rb:15:in `request_call'
                 /home/vagrant/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/excon-0.31.0/lib/excon/middlewares/base.rb:15:in `request_call'
                 /home/vagrant/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/excon-0.31.0/lib/excon/middlewares/base.rb:15:in `request_call'
                 /home/vagrant/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/excon-0.31.0/lib/excon/connection.rb:265:in `request'
                 /home/vagrant/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/heroku-3.3.0/lib/heroku/client/organizations.rb:31:in `request'
                 /home/vagrant/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/heroku-3.3.0/lib/heroku/client/organizations.rb:76:in `get_orgs'
                 /home/vagrant/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/heroku-3.3.0/lib/heroku/command/base.rb:53:in `org'
                 /home/vagrant/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/heroku-3.3.0/lib/heroku/command/apps.rb:237:in `create'
                 /home/vagrant/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/heroku-3.3.0/lib/heroku/command.rb:218:in `run'
                 /home/vagrant/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/heroku-3.3.0/lib/heroku/cli.rb:28:in `start'
                 /home/vagrant/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/heroku-3.3.0/bin/heroku:17:in `<top (required)>'
                 /home/vagrant/.rbenv/versions/2.0.0-p353/bin/heroku:23:in `load'
                 /home/vagrant/.rbenv/versions/2.0.0-p353/bin/heroku:23:in `<main>'

    Command:     heroku create nomster2-rochebox
    Version:     heroku-gem/3.3.0 (i686-linux) ruby/2.0.0

I did a heroku update through terminal (which was ok):

scimac13-11:vagrant christopherroche$ heroku update
Heroku CLI submits usage information back to Heroku. If you would like to disable this, set `skip_analytics: true` in /Users/christopherroche/.heroku/config.json
heroku-cli: Updating... done.
scimac13-11:vagrant christopherroche$ 

But that didnt solve the problem, so I would be grateful for any help you can give me on this problem.

Thank you!

**Comment by dickeyxxx** [comment]
are you behind a proxy?

**Comment by AndrewDESmith** [comment]
I'm running into the same problem, and am doing exercises from the same program.

We are running a Linux development environment inside Vagrant.  Outside of that, I'm not running any proxies or VPNs.

**Comment by sungwon** [comment]
`gem uninstall heroku`
and then
`gem install heroku`

If you're not using vagrant, rather than reinstalling heroku as a gem, it would probably be better to install the heroku toolbelt, but vagrant makes that difficult.

Here is some more info and other solutions:
http://stackoverflow.com/questions/17268517/heroku-client-internal-error-unable-to-verify-certificate
