### ISSUE TITLE
Heroku login: client internal error SocketError

### ISSUE THREAD

**Issue by ichromanraditya** [heroku/heroku#1976]
Hi. 
I'm using Ubuntu 14.04 64bit and when I try to use heroku at first time, I type 'heroku login' and got this error:

`heroku-cli: Installing CLI...
Error: getaddrinfo: Name or service not known (SocketError)
/usr/local/heroku/vendor/gems/excon-0.47.0/lib/excon/socket.rb:108:in `getaddrinfo'
/usr/local/heroku/vendor/gems/excon-0.47.0/lib/excon/socket.rb:108:in `connect'
/usr/local/heroku/vendor/gems/excon-0.47.0/lib/excon/ssl_socket.rb:148:in `connect'
/usr/local/heroku/vendor/gems/excon-0.47.0/lib/excon/socket.rb:28:in `initialize'
/usr/local/heroku/vendor/gems/excon-0.47.0/lib/excon/ssl_socket.rb:8:in `initialize'
/usr/local/heroku/vendor/gems/excon-0.47.0/lib/excon/connection.rb:387:in `new'
/usr/local/heroku/vendor/gems/excon-0.47.0/lib/excon/connection.rb:387:in `socket'
/usr/local/heroku/vendor/gems/excon-0.47.0/lib/excon/connection.rb:106:in `request_call'
/usr/local/heroku/vendor/gems/excon-0.47.0/lib/excon/middlewares/mock.rb:47:in `request_call'
/usr/local/heroku/vendor/gems/excon-0.47.0/lib/excon/middlewares/instrumentor.rb:25:in `request_call'
/usr/local/heroku/vendor/gems/excon-0.47.0/lib/excon/middlewares/base.rb:15:in `request_call'
/usr/local/heroku/vendor/gems/excon-0.47.0/lib/excon/middlewares/base.rb:15:in `request_call'
/usr/local/heroku/vendor/gems/excon-0.47.0/lib/excon/middlewares/base.rb:15:in `request_call'
/usr/local/heroku/vendor/gems/excon-0.47.0/lib/excon/connection.rb:233:in `request'
/usr/local/heroku/vendor/gems/excon-0.47.0/lib/excon.rb:230:in `get'
/usr/local/heroku/lib/heroku/jsplugin.rb:246:in `manifest'
/usr/local/heroku/lib/heroku/jsplugin.rb:259:in `url'
/usr/local/heroku/lib/heroku/jsplugin.rb:149:in `block (2 levels) in setup'
/usr/local/heroku/lib/heroku/jsplugin.rb:137:in `open'
/usr/local/heroku/lib/heroku/jsplugin.rb:137:in `block in setup'
/usr/lib/ruby/1.9.1/tmpdir.rb:83:in `mktmpdir'
/usr/local/heroku/lib/heroku/jsplugin.rb:135:in `setup'
/usr/local/heroku/lib/heroku/cli.rb:27:in `start'
/usr/bin/heroku:25:in `<main>'

retrying...
!    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       getaddrinfo: Name or service not known (SocketError) (Excon::Errors::SocketError)
    Command:     heroku login
    Version:     heroku-toolbelt/3.43.5 (x86_64-linux) ruby/1.9.3
    Error ID:    c95e15da8ae148a094add238873d6a0f

    More information in /root/.heroku/error.log
`

Please help

**Comment by ransombriggs** [comment]
@ichromanraditya it is failing when trying to look up the host `cli-assets.heroku.com`.  Could you please try again as it may be a temporary DNS issue.

**Comment by ichromanraditya** [comment]
Yeah seems it's a DNS issue, today I use different ISP and it's working. Thanks for your help!

**Comment by AgungPambudi** [comment]
The solution is changing your DNS name server. I was tried changing my DNS name server in my laptop in order to use Google DNS

Google DNS
Preferred: 8.8.8.8
Alternate: 8.8.4.4

And the result is works perfectly

**Comment by ichromanraditya** [comment]
It's solved mas @AgungPambudi . anyway thanks dah respon :)
