### ISSUE TITLE
problems

### ISSUE THREAD

**Issue by lishitianxia1385** [heroku/heroku#2009]
heroku-cli: Installing CLI... 0.32MB/18.54MB
Error: An existing connection was forcibly closed by the remote host. (Errno::EC
ONNRESET)
C:/Program Files (x86)/Heroku/ruby-2.1.7/lib/ruby/2.1.0/openssl/buffering.rb:182
:in `sysread_nonblock'
C:/Program Files (x86)/Heroku/ruby-2.1.7/lib/ruby/2.1.0/openssl/buffering.rb:182
:in `read_nonblock'
C:/Program Files (x86)/Heroku/vendor/gems/excon-0.51.0/lib/excon/socket.rb:158:i
n `read_nonblock'
C:/Program Files (x86)/Heroku/vendor/gems/excon-0.51.0/lib/excon/socket.rb:35:in
 `read'
C:/Program Files (x86)/Heroku/vendor/gems/excon-0.51.0/lib/excon/response.rb:149
:in `parse'
C:/Program Files (x86)/Heroku/vendor/gems/excon-0.51.0/lib/excon/middlewares/res
ponse_parser.rb:6:in `response_call'
C:/Program Files (x86)/Heroku/vendor/gems/excon-0.51.0/lib/excon/connection.rb:3
89:in `response'
C:/Program Files (x86)/Heroku/vendor/gems/excon-0.51.0/lib/excon/connection.rb:2
53:in `request'
C:/Program Files (x86)/Heroku/vendor/gems/excon-0.51.0/lib/excon.rb:238:in `get'

C:/Program Files (x86)/Heroku/lib/heroku/jsplugin.rb:149:in `block (2 levels) in
 setup'
C:/Program Files (x86)/Heroku/lib/heroku/jsplugin.rb:137:in `open'
C:/Program Files (x86)/Heroku/lib/heroku/jsplugin.rb:137:in `block in setup'
C:/Program Files (x86)/Heroku/ruby-2.1.7/lib/ruby/2.1.0/tmpdir.rb:88:in `mktmpdi
r'
C:/Program Files (x86)/Heroku/lib/heroku/jsplugin.rb:135:in `setup'
C:/Program Files (x86)/Heroku/lib/heroku/cli.rb:27:in `start'
C:/Program Files (x86)/Heroku/bin/heroku:29:in `<main>'

retrying...
heroku-cli: Installing CLI... 18.54MB/18.54MB !    Heroku client internal error.

 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       SHA mismatch for heroku.tar.gz (RuntimeError)
    Command:     heroku login
    Version:     heroku/toolbelt/3.43.9 (i386-mingw32) ruby/2.1.7
    Error ID:    d317185d8e4e4dd3865cd2c302fcf9c0

    More information in C:/Users/Geek Lee/.heroku/error.log

**Comment by ransombriggs** [comment]
@lishitianxia1385 could you please try again?  This was most likely a temporary network error.

**Comment by ransombriggs** [comment]
@lishitianxia1385 also, are you running any anti-virus software?

**Comment by lishitianxia1385** [comment]
Yes, I was in China. Networks need to scale the wall, the network is very poor, especially with the command-line to download heroku-cli, but the download heroku-toolbelt is normal from the web, the network itself is not bad. Hope can be downloaded from the website heroku-cli, I can install it manually. Thank you for your answer.

**Comment by trimble** [comment]
This looks like an issue that turned out to be a networking issue. @ghost, can we close it?
