### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by tranlamnhatnam** [heroku/heroku#2012]
Hello.

After install Heroku Toobelt. I downloaded it from https://toolbelt.heroku.com/windows. I open Gist Bast and try `heroku login` but it return error:

```
C:/Program Files (x86)/Heroku/ruby-2.1.7/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- ffi (LoadError)
        from C:/Program Files (x86)/Heroku/ruby-2.1.7/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Program Files (x86)/Heroku/vendor/gems/rest-client-1.8.0/lib/restclient/windows/root_certs.rb:2:in `<top (required)>'
        from C:/Program Files (x86)/Heroku/vendor/gems/rest-client-1.8.0/lib/restclient/windows.rb:7:in `require_relative'
        from C:/Program Files (x86)/Heroku/vendor/gems/rest-client-1.8.0/lib/restclient/windows.rb:7:in `<top (required)>'
        from C:/Program Files (x86)/Heroku/ruby-2.1.7/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Program Files (x86)/Heroku/ruby-2.1.7/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Program Files (x86)/Heroku/vendor/gems/rest-client-1.8.0/lib/restclient.rb:16:in `<top (required)>'
        from C:/Program Files (x86)/Heroku/ruby-2.1.7/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Program Files (x86)/Heroku/ruby-2.1.7/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Program Files (x86)/Heroku/vendor/gems/rest-client-1.8.0/lib/rest_client.rb:2:in `<top (required)>'
        from C:/Program Files (x86)/Heroku/ruby-2.1.7/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Program Files (x86)/Heroku/ruby-2.1.7/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Program Files (x86)/Heroku/lib/heroku/command.rb:8:in `<top (required)>'
        from C:/Program Files (x86)/Heroku/ruby-2.1.7/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Program Files (x86)/Heroku/ruby-2.1.7/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Program Files (x86)/Heroku/lib/heroku/client.rb:4:in `<top (required)>'
        from C:/Program Files (x86)/Heroku/ruby-2.1.7/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Program Files (x86)/Heroku/ruby-2.1.7/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Program Files (x86)/Heroku/lib/heroku/auth.rb:3:in `<top (required)>'
        from C:/Program Files (x86)/Heroku/ruby-2.1.7/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Program Files (x86)/Heroku/ruby-2.1.7/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Program Files (x86)/Heroku/lib/heroku/analytics.rb:1:in `<top (required)>'
        from C:/Program Files (x86)/Heroku/ruby-2.1.7/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Program Files (x86)/Heroku/ruby-2.1.7/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Program Files (x86)/Heroku/lib/heroku/cli.rb:13:in `<top (required)>'
        from C:/Program Files (x86)/Heroku/ruby-2.1.7/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Program Files (x86)/Heroku/ruby-2.1.7/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Program Files (x86)/Heroku/bin/heroku:27:in `<main>'
```

I run on Windows 10 64-bit, before install Heroku Toolbelt, i have a Ruby version installed in `c:\Ruby23-x64`

How can i fix this error?

**Comment by Eldinnie** [comment]
Same problem here, Fresh install of windows 10 64bit. Someone noticed it might be due to gem installation rules in Ruby 2.1

**Comment by ransombriggs** [comment]
On phone: just shipped a new release that rolls back the release with this bug, please re install from https://toolbelt.heroku.com

**Comment by ransombriggs** [comment]
@Eldinnie & @tranlamnhatnam a fresh install from the website should work now

**Comment by tranlamnhatnam** [comment]
Thanks! It's worked for me.

**Comment by Eldinnie** [comment]
Worked for me aswell, thanks @tranlamnhatnam
