### ISSUE TITLE
Heroku toolbelt CLI

### ISSUE THREAD

**Issue by Rhyngoh** [heroku/heroku#2023]
I'm very very new to coding and can't even get the programs installed >< I was trying to install the heroku-cli but it just times out and goes on an infinite loop to try to get it installed. I just downloaded it and put heroku into the command prompt. How do I go about fixing this? 

```
C:\WINDOWS\system32>heroku
heroku-cli: Installing CLI...
Error: connect_write timeout reached
C:/Program Files (x86)/Heroku/vendor/gems/excon-0.51.0/lib/excon/socket.rb:266:in `select_with_timeout'
C:/Program Files (x86)/Heroku/vendor/gems/excon-0.51.0/lib/excon/socket.rb:130:in `rescue in block in connect'
C:/Program Files (x86)/Heroku/vendor/gems/excon-0.51.0/lib/excon/socket.rb:111:in `block in connect'
C:/Program Files (x86)/Heroku/vendor/gems/excon-0.51.0/lib/excon/socket.rb:102:in `each'
C:/Program Files (x86)/Heroku/vendor/gems/excon-0.51.0/lib/excon/socket.rb:102:in `connect'
C:/Program Files (x86)/Heroku/vendor/gems/excon-0.51.0/lib/excon/ssl_socket.rb:146:in `connect'
C:/Program Files (x86)/Heroku/vendor/gems/excon-0.51.0/lib/excon/socket.rb:28:in `initialize'
C:/Program Files (x86)/Heroku/vendor/gems/excon-0.51.0/lib/excon/ssl_socket.rb:8:in `initialize'
C:/Program Files (x86)/Heroku/vendor/gems/excon-0.51.0/lib/excon/connection.rb:404:in `new'
C:/Program Files (x86)/Heroku/vendor/gems/excon-0.51.0/lib/excon/connection.rb:404:in `socket'
C:/Program Files (x86)/Heroku/vendor/gems/excon-0.51.0/lib/excon/connection.rb:106:in `request_call'
C:/Program Files (x86)/Heroku/vendor/gems/excon-0.51.0/lib/excon/middlewares/mock.rb:47:in `request_call'
C:/Program Files (x86)/Heroku/vendor/gems/excon-0.51.0/lib/excon/middlewares/instrumentor.rb:25:in `request_call'
C:/Program Files (x86)/Heroku/vendor/gems/excon-0.51.0/lib/excon/middlewares/base.rb:15:in `request_call'
C:/Program Files (x86)/Heroku/vendor/gems/excon-0.51.0/lib/excon/middlewares/base.rb:15:in `request_call'
C:/Program Files (x86)/Heroku/vendor/gems/excon-0.51.0/lib/excon/middlewares/base.rb:15:in `request_call'
C:/Program Files (x86)/Heroku/vendor/gems/excon-0.51.0/lib/excon/connection.rb:250:in `request'
C:/Program Files (x86)/Heroku/vendor/gems/excon-0.51.0/lib/excon.rb:238:in `get'
C:/Program Files (x86)/Heroku/lib/heroku/jsplugin.rb:255:in `manifest'
C:/Program Files (x86)/Heroku/lib/heroku/jsplugin.rb:268:in `url'
C:/Program Files (x86)/Heroku/lib/heroku/jsplugin.rb:158:in `block (2 levels) in setup'
C:/Program Files (x86)/Heroku/lib/heroku/jsplugin.rb:146:in `open'
C:/Program Files (x86)/Heroku/lib/heroku/jsplugin.rb:146:in `block in setup'
C:/Program Files (x86)/Heroku/ruby-2.1.7/lib/ruby/2.1.0/tmpdir.rb:88:in `mktmpdir'
C:/Program Files (x86)/Heroku/lib/heroku/jsplugin.rb:144:in `setup'
C:/Program Files (x86)/Heroku/lib/heroku/cli.rb:27:in `start'
C:/Program Files (x86)/Heroku/bin/heroku:29:in `<main>'
```
retrying...

**Comment by ransombriggs** [comment]
@Rhyngoh the CLI pulls down extra software the first time that it runs and it appears that it had issues downloading said software.  It is a timeout, which may just be a temporary network issue, or it could possibly a firewall or other network configuration like a proxy server.   I would try again, to see it works now.

**Comment by Rhyngoh** [comment]
I realized I just had to turn off my firewall to let it install. Closing thread now.
