### ISSUE TITLE
Error updating heroku cli on windows

### ISSUE THREAD

**Issue by carduque** [heroku/heroku#2045]
heroku-cli: Installing CLI... 18.53MB/18.53MB !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       Permission denied @ rb_sysopen - C:\Users\cduquemarcos\AppData\Local/heroku/cli/lib/node.exe (Errno::EACCES)
    Command:     heroku pg:psql
    Version:     heroku/toolbelt/3.43.9 (i386-mingw32) ruby/2.1.7
    Error ID:    89b9940dd4ed4da89c44a0963f48d64b

    More information in C:/Users/cduquemarcos/.heroku/error.log

CAT error.log:
Heroku client internal error.
Permission denied @ rb_sysopen - C:\Users\cduquemarcos\AppData\Local/heroku/cli/lib/node.exe
C:/Users/cduquemarcos/.heroku/client/lib/heroku/jsplugin.rb:179:in `initialize'
C:/Users/cduquemarcos/.heroku/client/lib/heroku/jsplugin.rb:179:in `open'
C:/Users/cduquemarcos/.heroku/client/lib/heroku/jsplugin.rb:179:in `block (4 levels) in setup'
C:/Program Files (x86)/Heroku/ruby-2.1.7/lib/ruby/2.1.0/rubygems/package/tar_reader.rb:64:in `each'
C:/Users/cduquemarcos/.heroku/client/lib/heroku/jsplugin.rb:170:in `block (3 levels) in setup'
C:/Program Files (x86)/Heroku/ruby-2.1.7/lib/ruby/2.1.0/rubygems/package/tar_reader.rb:28:in `new'
C:/Users/cduquemarcos/.heroku/client/lib/heroku/jsplugin.rb:168:in `block (2 levels) in setup'
C:/Users/cduquemarcos/.heroku/client/lib/heroku/jsplugin.rb:167:in `open'
C:/Users/cduquemarcos/.heroku/client/lib/heroku/jsplugin.rb:167:in `block in setup'
C:/Program Files (x86)/Heroku/ruby-2.1.7/lib/ruby/2.1.0/tmpdir.rb:88:in `mktmpdir'
C:/Users/cduquemarcos/.heroku/client/lib/heroku/jsplugin.rb:135:in `setup'
C:/Users/cduquemarcos/.heroku/client/lib/heroku/cli.rb:27:in `start'
C:/Program Files (x86)/Heroku/bin/heroku:29:in `<main>'

**Comment by dickeyxxx** [comment]
This is likely a problem with your antivirus

**Comment by carduque** [comment]
I'm fixing it removing folder C:\Users\cduquemarcos\AppData\Local\heroku
But it is happening once-twice a week. Very Annoying.

**Comment by ransombriggs** [comment]
@carduque what antivirus software are you using?

**Comment by carduque** [comment]
Sophos

**Comment by wooyek** [comment]
This also happens when antivirus is disabled
