### ISSUE TITLE
`heroku status` should fail gracefully when status is down

### ISSUE THREAD

**Issue by ddollar** [heroku/heroku#364]
[12:15:50] <bau> hi all, when i type: heroku status on ubuntu I have this error: === Heroku Status
    [12:15:50] <bau> /usr/local/heroku/lib/heroku/command/status.rb:26:in `index': undefined method `[]' for nil:NilClass (NoMethodError)
    [12:15:50] <bau> from /usr/local/heroku/lib/heroku/command.rb:167:in `run'
    [12:15:50] <bau> from /usr/local/heroku/lib/heroku/cli.rb:9:in `start'
    [12:15:50] <bau> from /usr/bin/heroku:30:in `<main>'

**Comment by dickeyxxx** [comment]
it does now

**Comment by dickeyxxx** [comment]
but this is super old so that's not surprising
