### ISSUE TITLE
CLI crashes when platform is down

### ISSUE THREAD

**Issue by cberner** [heroku/heroku#417]
During the current downtime the CLI crashes with a backtrace, instead of giving an error message indicating that the Heroku platform is down.

```
christopher@penryn:~/Code/dcbtech/mainsite$ heroku pg:psql
 !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       EOFError (Excon::Errors::SocketError)
    Backtrace:   /usr/lib/ruby/1.9.1/openssl/buffering.rb:246:in `readline'
                 /usr/local/heroku/vendor/gems/excon-0.14.2/lib/excon/response.rb:22:in `parse'
                 /usr/local/heroku/vendor/gems/excon-0.14.2/lib/excon/connection.rb:255:in `request_kernel'
                 /usr/local/heroku/vendor/gems/excon-0.14.2/lib/excon/connection.rb:101:in `request'
                 /usr/local/heroku/vendor/gems/heroku-api-0.2.6/lib/heroku/api.rb:60:in `request'
                 /usr/local/heroku/lib/heroku/auth.rb:19:in `request'
                 /usr/local/heroku/vendor/gems/heroku-api-0.2.6/lib/heroku/api/config_vars.rb:18:in `get_config_vars'
                 /usr/local/heroku/lib/heroku/helpers/heroku_postgresql.rb:9:in `app_config_vars'
                 /usr/local/heroku/lib/heroku/helpers/heroku_postgresql.rb:41:in `hpg_resolve'
                 /usr/local/heroku/lib/heroku/command/pg.rb:68:in `psql'
                 /usr/local/heroku/lib/heroku/command.rb:178:in `run'
                 /usr/local/heroku/lib/heroku/cli.rb:19:in `start'
                 /usr/bin/heroku:26:in `<main>'

    Command:     heroku pg:psql
    Version:     heroku-toolbelt/2.28.7 (i686-linux) ruby/1.9.3
```

**Comment by dickeyxxx** [comment]
I'm going to close this because there really isn't a reliable way to know if the API is having problems without calling `heroku status`. (It could be a `getaddrinfo` issue, but that's rarely the case)
