### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by cookiescrumbs** [heroku/heroku#713]
Password (typing will be hidden): 
 !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

```
Error:       Unable to verify certificate, please set `Excon.defaults[:ssl_ca_path] = path_to_certs`, `Excon.defaults[:ssl_ca_file] = path_to_file`, or `Excon.defaults[:ssl_verify_peer] = false` (less secure). (Excon::Errors::SocketError)
Backtrace:   /Users/cooks20/.heroku/client/vendor/gems/excon-0.16.10/lib/excon/ssl_socket.rb:60:in `connect'
             /Users/cooks20/.heroku/client/vendor/gems/excon-0.16.10/lib/excon/ssl_socket.rb:60:in `initialize'
             /Users/cooks20/.heroku/client/vendor/gems/excon-0.16.10/lib/excon/connection.rb:364:in `new'
             /Users/cooks20/.heroku/client/vendor/gems/excon-0.16.10/lib/excon/connection.rb:364:in `socket'
             /Users/cooks20/.heroku/client/vendor/gems/excon-0.16.10/lib/excon/connection.rb:192:in `request_kernel'
             /Users/cooks20/.heroku/client/vendor/gems/excon-0.16.10/lib/excon/connection.rb:103:in `request'
             /Users/cooks20/.heroku/client/vendor/gems/heroku-api-0.3.7/lib/heroku/api.rb:74:in `request'
             /Users/cooks20/.heroku/client/vendor/gems/heroku-api-0.3.7/lib/heroku/api/login.rb:9:in `post_login'
             /Users/cooks20/.heroku/client/lib/heroku/auth.rb:80:in `api_key'
             /Users/cooks20/.heroku/client/lib/heroku/auth.rb:189:in `ask_for_credentials'
             /Users/cooks20/.heroku/client/lib/heroku/auth.rb:221:in `ask_for_and_save_credentials'
             /Users/cooks20/.heroku/client/lib/heroku/auth.rb:84:in `get_credentials'
             /Users/cooks20/.heroku/client/lib/heroku/auth.rb:41:in `login'
             /Users/cooks20/.heroku/client/lib/heroku/command/auth.rb:31:in `login'
             /Users/cooks20/.heroku/client/lib/heroku/command.rb:206:in `run'
             /Users/cooks20/.heroku/client/lib/heroku/cli.rb:28:in `start'
             /usr/bin/heroku:24:in `<main>'

Command:     heroku login
Version:     heroku-toolbelt/2.35.0 (x86_64-darwin10.8.0) ruby/1.9.3
```

**Comment by trimble** [comment]
This seems to be resolved. Can we close it?
